// 本地教学页面。AI 问答通过同源 /api/chat 完成。
const candidates = [
  {id:'C001',name:'槲皮素',en:'Quercetin',cid:5280343,formula:'C15H10O7',pmid:'34572484',context:'EGFR C797S 耐药非小细胞肺癌的细胞和移植瘤模型',finding:'摘要提出 AXL 相关机制。',limit:'不能据此说已证实直接抑制 EGFR。',status:'文献支持 · 特定模型'},
  {id:'C002',name:'木犀草素',en:'Luteolin',cid:5280445,formula:'C15H10O6',pmid:'24471765',context:'EGFR L858R/T790M 耐药非小细胞肺癌的细胞和小鼠模型',finding:'摘要报告与突变 EGFR 降解及 Hsp90 相互作用有关。',limit:'结果仅适用于论文的实验条件，不能外推为临床疗效。',status:'文献支持 · 特定模型'},
  {id:'C003',name:'黄芩素',en:'Baicalein',cid:5281605,formula:'C15H10O5',pmid:'27586635',context:'非小细胞肺癌 H-460 细胞和小鼠模型',finding:'这篇摘要重点讨论 VEGF 等变化。',limit:'不能仅凭此文标为直接作用 EGFR 已验证；黄芩素与黄芩苷是不同分子。',status:'肺癌相关 · EGFR 待核验'}
];
const steps=[['task','target','研究需求输入'],['evidence','library-big','分析与证据'],['ranking','list-filter','候选与排序'],['experiment','flask-conical','验证方案'],['report','clipboard-check','结果与报告']];
const DEFAULT_AGENT_URL='https://yuanqi.tencent.com/webim/#/chat/vcaDuu?appid=2103722870126603328&experience=true';
const makeSessionId=()=>{try{return crypto.randomUUID();}catch{return 'herblab-'+Date.now()+'-'+Math.random().toString(16).slice(2);}};
const STORAGE_KEY='qizhen-research-v1';
const initial=()=>({mode:'general',selected:'C002',analysisCandidate:'',reason:'',demand:'',target:'',scope:'',goal:'候选筛选与证据分析',analysis:{reply:'',submittedAt:'',loading:false,error:''},notes:{},reviewed:{},experiment:{hypothesis:'',model:'',controls:'',readouts:'',plan:''},result:{observation:'',data:'',interpretation:'',nextStep:''},agentUrl:DEFAULT_AGENT_URL,updated:'',chat:{messages:[],draft:'',userId:makeSessionId()}});
let state=initial();
try { const current=localStorage.getItem(STORAGE_KEY),legacy=!current&&localStorage.getItem('herblab-egfr-v1');const saved=JSON.parse(current||legacy); if(saved&&typeof saved==='object') state={...state,...saved,...(legacy?{mode:'case'}:{})}; } catch {}
// 兼容尚未配置链接的旧草稿，保留学生笔记。
if(typeof state.agentUrl!=='string'||!state.agentUrl.trim()) state.agentUrl=DEFAULT_AGENT_URL;
if(!state.chat||typeof state.chat!=='object') state.chat=initial().chat;
if(!Array.isArray(state.chat.messages)) state.chat.messages=[];
if(typeof state.chat.draft!=='string') state.chat.draft='';
if(typeof state.chat.userId!=='string'||!state.chat.userId) state.chat.userId=makeSessionId();
if(typeof state.demand!=='string')state.demand=initial().demand;
if(!['general','case'].includes(state.mode))state.mode='general';
for(const key of ['target','scope','goal','analysisCandidate'])if(typeof state[key]!=='string')state[key]=initial()[key];
state.analysis={...initial().analysis,...(state.analysis||{}),loading:false,error:''};
state.experiment={...initial().experiment,...(state.experiment||{})};
state.result={...initial().result,...(state.result||{})};
state.chat.loading=false;
state.chat.error='';
state.chat.configured=undefined;
if(state.chat.messages.length&&state.chat.messages[state.chat.messages.length-1].role==='user'){
  state.chat.draft=state.chat.messages.pop().content||state.chat.draft;
}
let healthChecked=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>`<i data-lucide="${n}"></i>`;
const pubmed=c=>`https://pubmed.ncbi.nlm.nih.gov/${c.pmid}/`;
const pubchem=c=>`https://pubchem.ncbi.nlm.nih.gov/compound/${c.cid}`;
function save(){state.updated=new Date().toLocaleString('zh-CN');try{localStorage.setItem(STORAGE_KEY,JSON.stringify({...state,analysis:{reply:state.analysis.reply,submittedAt:state.analysis.submittedAt},chat:{messages:state.chat.messages,draft:state.chat.draft,userId:state.chat.userId}}));}catch{toast('当前浏览器未允许保存草稿');}}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),3000);}
function page(){const p=location.hash.slice(1);return p==='compare'||steps.some(s=>s[0]===p)?p:'task';}
const isCase=()=>state.mode==='case';
function heading(top,title,sub){return `<div class="page-heading"><span class="eyebrow">${top}</span><div class="heading-row"><h1>${title}</h1><span class="tag">${isCase()?'案例 01 / 肺癌 EGFR':'通用分析 / 任意疾病'}</span></div><p class="sub">${sub}</p></div>`;}
function actions(note,next,label){return `<div class="actionbar"><span>${note}</span><button class="primary" data-next="${next}">${label}${icon('arrow-right')}</button></div>`;}
function modePicker(){return `<div class="mode-switch"><button id="useGeneral" class="${isCase()?'':'active'}">${icon('search')}通用疾病分析</button><button id="loadCase" class="${isCase()?'active':''}">${icon('book-open-check')}案例 01 · 肺癌 EGFR</button></div>`;}
function taskView(){if(!isCase())return heading('01 / 研究需求输入','输入任意疾病或研究问题','系统会把研究需求提交给智能体进行探索性分析；来源、证据等级和计算结果仍需逐项核验。')+modePicker()+`
<section class="section flow-card"><div class="section-head"><h2>研究需求</h2><span class="pill neutral">通用模式</span></div><label>疾病或研究问题<textarea id="demand" placeholder="例如：分析阿尔茨海默病相关靶点，并寻找有文献线索的中药单体">${esc(state.demand)}</textarea></label><div class="form-grid general-fields"><label>指定靶点（选填）<input id="target" value="${esc(state.target)}" placeholder="例如：ACHE；不知道可以留空"></label><label>中药或单体范围（选填）<input id="scope" value="${esc(state.scope)}" placeholder="例如：黄酮类；不限定可留空"></label><label>研究目的<select id="goal"><option ${state.goal==='候选筛选与证据分析'?'selected':''}>候选筛选与证据分析</option><option ${state.goal==='疾病机制与靶点梳理'?'selected':''}>疾病机制与靶点梳理</option><option ${state.goal==='文献证据核验'?'selected':''}>文献证据核验</option><option ${state.goal==='验证方案设计'?'selected':''}>验证方案设计</option></select></label></div><div class="button-row"><button id="startAnalysis" class="primary" ${state.analysis.loading?'disabled':''}>${icon(state.analysis.loading?'loader-circle':'sparkles')}${state.analysis.loading?'正在分析…':'开始分析'}</button></div>${state.analysis.error?`<div class="chat-error">${esc(state.analysis.error)}</div>`:''}<p class="mini-note">通用回答不自动产生分子对接结果。只有获得同一靶点、同一协议的真实计算数据后，才会开放双排序。</p></section>
${state.analysis.reply?`<section class="section"><div class="section-head"><h2>最近一次分析</h2><span class="pill neutral">${esc(state.analysis.submittedAt||'已返回')}</span></div><div class="analysis-result">${esc(state.analysis.reply)}</div><div class="button-row"><button data-next="evidence" class="primary">查看完整结果${icon('arrow-right')}</button></div></section>`:''}
<section class="section"><div class="section-head"><h2>已有核验案例</h2><span class="pill neutral">可随时切换</span></div><p>肺癌 EGFR 案例保留三种已核验候选、统一对接和教学双排序，用于演示完整流程及检查系统是否正常。</p><button id="openCase">进入案例 01</button></section>`;
return heading('01 / 案例研究需求','肺癌 EGFR 教学案例','本案例用于演示已核验资料、同协议对接和双排序，不代表平台只能分析肺癌。')+modePicker()+`
<section class="section flow-card"><div class="section-head"><h2>案例边界</h2><span class="pill neutral">已核验案例</span></div><label>案例研究问题<textarea id="demand" placeholder="比较肺癌 EGFR 相关中药单体的证据与候选顺序">${esc(state.demand||'比较肺癌 EGFR 相关的中药单体，查看文献证据与两条候选排序路径。')}</textarea></label><div class="form-grid flow-fields"><div><span class="field-caption">疾病场景</span><strong>肺癌 / 非小细胞肺癌</strong></div><div><span class="field-caption">教学靶点</span><strong>EGFR · 2ITW 野生型结构</strong></div></div><p class="mini-note">案例数据不会被自动套用到其他疾病。切回通用模式可以提交新的疾病问题。</p></section>
<section class="section"><div class="section-head"><h2>本节目标</h2><span class="pill neutral">固定教学案例</span></div>
<p>阅读三种候选分子的样例论文，区分“肺癌相关”“涉及 EGFR 突变模型”与“直接作用 EGFR 已证实”。选择一条候选，写下依据和仍需核验的问题。</p>
<div class="stats"><div class="stat"><span>已核验候选</span><strong>03</strong><small>本地案例资料</small></div><div class="stat green"><span>样例论文</span><strong>03</strong><small>各一篇</small></div><div class="stat"><span>教学工作流</span><strong>01</strong><small>腾讯元器中已调试</small></div></div>
<div class="target-info">${icon('info')}<span>双排序已载入 EGFR 2ITW 同协议教学对接与统一检索数据。当前门槛 45 可展示三候选排名；参数未经科学校准，完整风险筛查尚未完成。请到“双排序”查看依据与参数。</span></div></section>
<section class="section"><div class="section-head"><h2>完整研学路径</h2></div><ol class="plan"><li><span class="number">1</span><div><h3>文献检索与核验</h3><p>阅读现有三篇样例文献，检查 PMID 和证据边界。</p></div>${icon('book-open-text')}</li><li><span class="number">2</span><div><h3>两条路径选候选</h3><p>比较最匹配与非热门排序，查看参数和原始输入。</p></div>${icon('list-filter')}</li><li><span class="number">3</span><div><h3>设计实验并回填结果</h3><p>形成待讨论方案，记录真实实验观察，导出完整报告。</p></div>${icon('flask-conical')}</li></ol></section>${actions('资料核验日期：2026-09-26','evidence','查看文献')}`;}
function compareView(){return heading('CANDIDATE COMPARISON / 候选对比','三种候选，三种证据语境','逐条查看来源，再判断文献到底支持什么。')+`
<section class="section"><div class="section-head"><h2>候选资料</h2><small>PubChem + 对应 PubMed 摘要</small></div><div class="table-scroll"><table><thead><tr><th>候选</th><th>PubChem CID</th><th>分子式</th><th>样例文献</th><th>证据状态</th></tr></thead><tbody>${candidates.map(c=>`<tr><td><strong>${c.name}</strong><small>${c.en}</small></td><td><a href="${pubchem(c)}" target="_blank" rel="noopener noreferrer">${c.cid}</a></td><td>${c.formula}</td><td><a href="${pubmed(c)}" target="_blank" rel="noopener noreferrer">PMID ${c.pmid}</a></td><td><span class="pill ${c.id==='C003'?'warn':''}">${c.status}</span></td></tr>`).join('')}</tbody></table></div><p class="mini-note">一篇样例论文不等于该分子的文献总数。手机上可左右滑动表格。</p></section>
<section class="section"><div class="section-head"><h2>查看双排序</h2></div><p>检查统一对接、过滤和文献热度数据，比较常规与冷门排名。</p><button class="primary" data-next="ranking">进入双排序</button></section><section class="section"><div class="section-head"><h2>思考题</h2></div><div class="evidence-item"><h3>哪两篇论文涉及 EGFR 突变模型？</h3><p>它们报告的机制有何不同？为什么第三篇不能算直接作用 EGFR 的证据？</p><button class="primary" data-next="evidence">研读证据 ${icon('arrow-right')}</button></div></section>`;}
function evidenceView(){return heading('02 / 文献检索结果','把结论放回研究条件中','当前展示已核对的三篇样例论文；这里不会按输入框内容实时检索 PubMed。')+`<div class="flow-notice">${icon('search')}<span>检索结果来自肺癌 EGFR 固定教学资料。每种分子各展示一篇样例论文，不能当作文献总量。</span></div>`+candidates.map(c=>`
<article class="evidence-item"><div class="evidence-top"><div><h3>${c.name} <span class="sub">${c.en}</span></h3><p>${esc(c.context)}</p></div><span class="pill ${c.id==='C003'?'warn':''}">${c.status}</span></div>
<p><strong>摘要要点：</strong>${esc(c.finding)}</p><p><strong>判断边界：</strong>${esc(c.limit)}</p><div class="evidence-links"><a href="${pubmed(c)}" target="_blank" rel="noopener noreferrer">查看 PMID ${c.pmid} ${icon('external-link')}</a><a href="${pubchem(c)}" target="_blank" rel="noopener noreferrer">查看 PubChem ${icon('external-link')}</a></div>
<label>我的证据笔记<textarea data-note="${c.id}" placeholder="记录研究模型、结果、局限或追问…">${esc(state.notes[c.id]||'')}</textarea></label><label class="check-label"><input type="checkbox" data-reviewed="${c.id}" ${state.reviewed[c.id]?'checked':''}>我已阅读并记录这条资料</label></article>`).join('')+`
<section class="section"><div class="section-head"><h2>向智能体追问</h2></div><p>把这道问题送入右侧研习助手，回答会保留在当前学习工作台。</p><div class="prompt-box" id="samplePrompt">槲皮素与木犀草素的样例论文都涉及 EGFR 突变模型，它们报告的机制有什么不同？黄芩素为什么不能仅凭这篇论文标为 EGFR 已验证？请分别给出 PMID 和结论适用范围。</div><div class="button-row"><button id="copyPrompt">${icon('copy')}复制提问</button><button id="askAgent" class="primary">${icon('message-circle')}向智能体提问</button></div></section>${actions('核对原文后再判断候选','ranking','查看两条筛选路径')}`;}
function genericEvidenceView(){return heading('02 / 分析与证据','查看智能体返回的探索性分析','通用结果用于形成检索和验证方向；未给出可核对来源的内容应标记为待核验。')+`
<div class="flow-notice">${icon('shield-check')}<span>当前结果来自智能体。只有明确列出可核对来源、检索日期和适用条件的内容，才能进一步进入候选数据集。</span></div>
${state.analysis.reply?`<section class="section"><div class="section-head"><h2>研究分析结果</h2><span class="pill neutral">${esc(state.analysis.submittedAt||'本次会话')}</span></div><div class="analysis-result">${esc(state.analysis.reply)}</div></section>`:`<section class="section empty-state"><div>${icon('search-x')}</div><h2>尚未生成分析结果</h2><p>请先返回研究需求页，输入疾病或研究问题并点击“开始分析”。</p><button data-next="task" class="primary">返回输入研究需求</button></section>`}
<section class="section"><div class="section-head"><h2>证据进入数据集前的检查</h2></div><ol class="check-list"><li>疾病、靶点和化合物名称是否经过标准化。</li><li>论文是否有可打开的 PMID、DOI 或正式链接。</li><li>细胞、动物、临床、对接或网络药理学证据是否明确区分。</li><li>模型提出的候选是否明确标记为“研究假设”。</li></ol></section>${actions('通用分析没有统一计算数据时不产生排名','ranking','检查候选与排序')}`;}
function genericRankingView(){return heading('03 / 候选与排序','当前不生成双排序','现有双排序只适用于肺癌 EGFR 案例的同靶点、同协议数据，不能套用到新的疾病问题。')+`
<section class="section empty-state"><div>${icon('list-x')}</div><h2>尚无可比较的统一计算数据</h2><p>需要先确认疾病和靶点，建立候选库，并在同一协议下补齐对接、风险过滤和统一文献热度，才能启用最匹配与非热门排序。</p><div class="button-row"><button data-next="evidence">返回分析结果</button><button id="openCase" class="primary">查看肺癌 EGFR 排名案例</button></div></section>
<section class="section"><div class="section-head"><h2>为什么暂不排名</h2></div><p>智能体文字回答不等于结构化计算结果。没有真实对接分数时显示名次会制造虚假精确性；文献少也不能直接等同于创新性高。</p></section>${actions('可以先记录待验证候选和假设','experiment','进入验证方案')}`;}
function experimentView(){if(!isCase())return heading('04 / 验证方案','把分析线索转成可审核的研究方案','这里记录候选、假设和验证思路，不会把智能体建议当成已执行实验。')+`
<section class="section flow-card"><div class="section-head"><h2>拟验证对象</h2><span class="pill neutral">通用分析</span></div><label>候选单体或研究对象<input id="analysisCandidate" value="${esc(state.analysisCandidate)}" placeholder="填写准备进一步核验的候选；没有可先留空"></label></section>
<section class="section flow-card"><div class="section-head"><h2>验证方案记录</h2><span class="pill warn">待导师确认</span></div><div class="form-grid">${[['hypothesis','待验证假设','明确疾病、靶点、候选及预期关系。'],['model','研究模型','拟采用什么模型？为何适合这一问题？'],['controls','对照设置','阳性、阴性及溶剂对照如何设置？'],['readouts','观察指标','用哪些指标区分现象与机制？'],['plan','方案与待确认事项','记录重复、分析方法、伦理与安全审核事项。']].map(([key,label,hint])=>`<label class="${key==='plan'?'full':''}">${label}<textarea data-experiment="${key}" placeholder="${hint}">${esc(state.experiment[key])}</textarea></label>`).join('')}</div><p class="mini-note">实验条件必须由具备资质的教师或实验人员审核；平台不提供自动执行。</p></section>${actions('方案保存在当前浏览器','report','进入结果与报告')}`;
return heading('04 / 湿实验设计','把候选变成可讨论的验证方案','以下是案例方案记录表。实验条件、伦理和安全要求需要导师审核，页面不会自动生成已执行结果。')+`
<section class="section flow-card"><div class="section-head"><h2>当前拟验证候选</h2><span class="pill neutral">方案草稿</span></div><label>选择候选<select id="selected">${candidates.map(c=>`<option value="${c.id}" ${state.selected===c.id?'selected':''}>${c.name} · ${c.id}</option>`).join('')}</select></label><p class="mini-note">选择候选只是确定讨论对象，不表示该分子已被实验验证。</p></section>
<section class="section flow-card"><div class="section-head"><h2>实验设计记录</h2><span class="pill warn">待导师确认</span></div><div class="form-grid">${[['hypothesis','待验证假设','准备验证什么？区分抗肿瘤表型与直接作用 EGFR。'],['model','研究模型','拟采用什么模型？为何适合这一问题？'],['controls','对照设置','阳性、阴性及溶剂对照如何设置？'],['readouts','观察指标','用哪些指标判断现象与机制？'],['plan','方案与待确认事项','记录重复、分析方法及需导师审核的条件。']].map(([key,label,hint])=>`<label class="${key==='plan'?'full':''}">${label}<textarea data-experiment="${key}" placeholder="${hint}">${esc(state.experiment[key])}</textarea></label>`).join('')}</div><p class="mini-note">这里只保存设计草稿，未提供实验操作指令或自动执行。</p></section>${actions('方案保存在当前浏览器','report','进入结果回填')}`;}
function reportText(){const c=candidates.find(x=>x.id===state.selected)||candidates[1];return `本草研习｜肺癌 EGFR 候选比较教学报告\n\n选择候选：${c.name}（${c.en}）\n样例论文：PMID ${c.pmid} ${pubmed(c)}\n研究语境：${c.context}\n我的判断：${state.reason||'未填写'}\n\n证据笔记：\n${candidates.map(x=>`${x.name} / PMID ${x.pmid}\n${state.notes[x.id]||'未填写'}`).join('\n\n')}\n\n局限：排序结果见以下记录；若数据缺失则不产生名次。教学评分不作临床疗效判断。\n\n${rankSummary()}\n导出时间：${new Date().toLocaleString('zh-CN')}`;}
function reportView(){const c=candidates.find(x=>x.id===state.selected)||candidates[1];return heading('LEARNING REPORT / 学习报告','写下你的判断','学生的本地报告草稿，可交给教师讨论。')+`
<div class="report"><span class="eyebrow">HERBLAB / CASE 01</span><h2>肺癌 EGFR 候选比较<br>教学报告</h2><div class="report-meta">本地草稿 · 资料核验于 2026-09-26</div><h3>01 / 选择候选</h3><label>我想讨论的分子<select id="selected">${candidates.map(x=>`<option value="${x.id}" ${state.selected===x.id?'selected':''}>${x.name} · PMID ${x.pmid}</option>`).join('')}</select></label><p>样例论文：<a href="${pubmed(c)}" target="_blank" rel="noopener noreferrer">PMID ${c.pmid}</a></p><h3>02 / 我的依据和疑问</h3><label><textarea id="reason" placeholder="论文研究了什么？支持什么结论？还不能判断什么？">${esc(state.reason)}</textarea></label><h3>03 / 双排序计算摘要</h3><pre class="rank-source">${esc(rankSummary())}</pre><h3>04 / 证据笔记完成情况</h3>${candidates.map(x=>{const ok=state.reviewed[x.id]&&(state.notes[x.id]||'').trim();return `<div class="feedback ${ok?'':'pending'}">${icon(ok?'circle-check':'circle-dashed')}<span>${x.name}：${ok?'已记录':'待补充'}</span></div>`;}).join('')}<p class="mini-note">完成情况由本地规则检查，不是 AI 评分；研究判断需教师结合原文审核。</p></div><div class="actionbar"><button data-next="evidence">${icon('arrow-left')}返回研读</button><button id="download" class="primary">${icon('download')}导出报告 .txt</button></div>`;}
function completeReportText(){if(isCase())return `用户需求：${state.demand||'未填写'}\n\n${reportText()}\n\n湿实验设计（待审核）\n${Object.entries({hypothesis:'待验证假设',model:'研究模型',controls:'对照设置',readouts:'观察指标',plan:'设计备注'}).map(([k,v])=>`${v}：${state.experiment[k]||'未填写'}`).join('\n')}\n\n实际结果回填\n${Object.entries({observation:'观察',data:'原始数据位置',interpretation:'解释与局限',nextStep:'下一步'}).map(([k,v])=>`${v}：${state.result[k]||'未填写'}`).join('\n')}`;
return `启真问智｜通用疾病研究分析报告\n\n研究问题：${state.demand||'未填写'}\n指定靶点：${state.target||'未限定'}\n候选范围：${state.scope||'未限定'}\n研究目的：${state.goal||'未填写'}\n拟验证对象：${state.analysisCandidate||'未填写'}\n\n智能体探索性分析\n${state.analysis.reply||'尚未生成'}\n\n重要边界\n当前通用分析未获得同一靶点、同一协议的计算数据，因此不生成对接排名。智能体提出的候选和机制必须通过数据库、原始文献或实验继续核验。\n\n验证方案（待审核）\n${Object.entries({hypothesis:'待验证假设',model:'研究模型',controls:'对照设置',readouts:'观察指标',plan:'设计备注'}).map(([k,v])=>`${v}：${state.experiment[k]||'未填写'}`).join('\n')}\n\n实际结果回填\n${Object.entries({observation:'观察',data:'原始数据位置',interpretation:'解释与局限',nextStep:'下一步'}).map(([k,v])=>`${v}：${state.result[k]||'未填写'}`).join('\n')}\n\n导出时间：${new Date().toLocaleString('zh-CN')}`;}
function resultView(){return heading('05 / 结果回填','记录实际观察，再整理报告','尚未开展实验时请留空；预测排名和 AI 回答不能作为实验结果。')+`
<section class="section flow-card"><div class="section-head"><h2>实验结果记录</h2><span class="pill neutral">当前浏览器保存</span></div><div class="form-grid">${[['observation','观察到什么','如尚未实验，请留空。'],['data','原始数据位置或编号','记录实验本或文件编号。'],['interpretation','结果解释与局限','结果支持什么？还有哪些其他解释？'],['nextStep','下一步验证','哪些问题需要重复或补充实验？']].map(([key,label,hint])=>`<label>${label}<textarea data-result="${key}" placeholder="${hint}">${esc(state.result[key])}</textarea></label>`).join('')}</div><p class="mini-note">本页不验证数据真实性。记录仅留在当前浏览器，导出后请自行保存。</p></section>
<section class="section flow-card"><div class="section-head"><h2>学习报告</h2><span class="pill neutral">可导出</span></div><label>我的证据判断<textarea id="reason" placeholder="现有信息支持什么，还有什么需要进一步核验？">${esc(state.reason)}</textarea></label>${isCase()?`<pre class="rank-source">${esc(rankSummary())}</pre>`:`<div class="target-info">${icon('info')}<span>通用分析尚无统一计算数据，本报告不会生成或展示双排序。</span></div>`}<div class="button-row"><button data-next="experiment">返回验证方案</button><button id="download" class="primary">${icon('download')}导出完整报告 .txt</button></div></section>`;}
function chatStatus(){if(location.protocol==='file:')return `<div class="chat-status warn">${icon('triangle-alert')}当前以文件方式打开。请访问 <a href="http://127.0.0.1:8787">http://127.0.0.1:8787</a>，并先运行项目根目录的“启动研学助手.cmd”。</div>`;if(state.chat.configured===true)return `<div class="chat-status ok">${icon('wifi')}智能体服务已配置</div>`;if(state.chat.configured===false)return `<div class="chat-status warn">${icon('triangle-alert')}智能体服务未配置，请检查服务端环境变量。</div>`;if(state.chat.configured==='unavailable')return `<div class="chat-status warn">${icon('triangle-alert')}暂时无法连接智能体服务，请确认服务已启动后重试。</div>`;return `<div class="chat-status">${icon('loader-circle')}正在检查智能体服务…</div>`;}
function assistantView(p){const generalTips={task:['通用研究入口','可以输入任意疾病。回答必须区分可核验证据、待核验线索和模型假设。'],ranking:['计算边界','没有同一靶点、同一协议的真实数据时不生成双排序。'],compare:['候选资料','先核对名称、结构和来源，再决定是否纳入候选库。'],evidence:['核验证据','优先检查 PMID、DOI、数据库链接、研究模型和结论边界。'],experiment:['方案讨论','先明确假设、模型、对照和观察指标，再交由导师审核。'],report:['结果核对','只填写真实获得的数据；AI回答不能作为实验结果。']};const caseTips={task:['案例边界','肺癌 EGFR 是已核验教学案例，不代表通用分析只支持该疾病。'],ranking:['解读候选','最匹配与非热门来自案例的同一批候选数据。'],compare:['候选资料','核对分子身份与来源，再决定进入哪条路径。'],evidence:['核验文献','点开 PMID 核对论文，智能体回答也需要与原文比对。'],experiment:['方案讨论','先写假设、模型、对照和观察指标，再请导师核对。'],report:['结果核对','只填写实际获得的数据；尚未实验的字段可以留空。']};const tips=(isCase()?caseTips:generalTips)[p]||generalTips.task;const msgs=state.chat.messages.map(m=>`<div class="chat-message ${m.role==='user'?'user':'bot'}"><span class="chat-role">${m.role==='user'?'你':'研习助手'}</span><div class="chat-text">${esc(m.content)}</div></div>`).join('');const err=state.chat.error?`<div class="chat-error" role="alert">${esc(state.chat.error)}<button id="retryChat">重试</button></div>`:'';return `<div class="assistant-title">${icon('sparkles')}研习助手<small>AI 问答</small></div><div class="assistant-body"><div class="assistant-kicker">${icon('compass')}当前步骤</div><h3>${tips[0]}</h3><p>${tips[1]}</p>${chatStatus()}<div id="chatMessages" class="chat-messages">${msgs||`<div class="chat-empty">还没有提问。输入问题后，智能体会返回可核对的文字回答。</div>`}${state.chat.loading?`<div class="chat-message bot"><span class="chat-role">研习助手</span><div class="chat-text chat-loading">正在检索并整理回答…</div></div>`:''}</div>${err}<label class="chat-compose"><span>你的问题</span><textarea id="chatDraft" rows="4" placeholder="${isCase()?'例如：黄芩素为何仍标记为 EGFR 待核验？':'例如：类风湿关节炎有哪些值得核验的靶点和中药单体线索？'}">${esc(state.chat.draft)}</textarea></label><div class="chat-actions"><button id="clearChat">${icon('trash-2')}清空对话</button><button id="sendChat" class="primary" ${state.chat.loading?'disabled':''}>${icon('send')}${state.chat.loading?'发送中…':'发送'} <small>Ctrl+Enter</small></button></div>${isCase()&&(p==='task'||p==='compare')?`<div class="molecule"><img src="quercetin.png" alt="槲皮素二维结构"><div class="molecule-label"><strong>槲皮素</strong><span>CID 5280343</span></div><p class="mini-note">案例结构示例 · PubChem</p></div>`:''}</div>${isCase()?`<a class="assistant-link" href="https://pubchem.ncbi.nlm.nih.gov/compound/5280343" target="_blank" rel="noopener noreferrer">查看案例结构来源 ${icon('arrow-up-right')}</a>`:''}`;}
async function checkHealth(){
 if(healthChecked||location.protocol==='file:')return;
 healthChecked=true;
 try{const res=await fetch('/api/health',{headers:{Accept:'application/json'},signal:AbortSignal.timeout(5000)});if(!res.ok)throw new Error();const data=await res.json();state.chat.configured=data.configured===true;}
 catch{state.chat.configured='unavailable';}
 render();
}
async function sendChat(){
 if(state.chat.loading)return;
 if(location.protocol==='file:'){state.chat.error='请先运行启动研学助手.cmd，并打开 http://127.0.0.1:8787 进行问答。';render();return;}
 const draft=(state.chat.draft||'').trim();
 if(!draft){document.querySelector('#chatDraft')?.focus();return;}
 if(draft.length>6000){state.chat.error='问题过长，请缩短到 6000 字符以内。';render();return;}
 state.chat.error='';state.chat.loading=true;
 const prior=state.chat.messages.slice(-38);
 state.chat.messages=[...prior,{role:'user',content:draft}];save();render();
 const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),100000);
 try{
  const res=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({messages:state.chat.messages,user_id:state.chat.userId}),signal:controller.signal});
  let data={};try{data=await res.json();}catch{}
  if(!res.ok||typeof data.reply!=='string'||!data.reply.trim())throw new Error(typeof data.error==='string'?data.error:`请求失败（${res.status}）`);
  state.chat.messages.push({role:'assistant',content:data.reply});state.chat.draft='';state.chat.error='';
 }catch(err){
  state.chat.messages=prior;
  state.chat.error=err.name==='AbortError'?'请求超时，请重试。':(err.message||'暂时无法连接智能体，请稍后重试。');
 }finally{clearTimeout(timer);state.chat.loading=false;save();render();document.querySelector('#chatDraft')?.focus();}
}
async function runAnalysis(){
 if(state.analysis.loading)return;
 if(location.protocol==='file:'){state.analysis.error='请先运行“启动研学助手.cmd”，并通过 http://127.0.0.1:8787 打开页面。';render();return;}
 const demand=(state.demand||'').trim();if(!demand){state.analysis.error='请先填写疾病或研究问题。';render();document.querySelector('#demand')?.focus();return;}
 const prompt=`你正在处理一个通用疾病科研教学问题。请不要默认使用肺癌或 EGFR 案例。\n研究问题：${demand}\n指定靶点：${state.target.trim()||'未指定，请根据证据提出待核验靶点'}\n候选范围：${state.scope.trim()||'未限定'}\n研究目的：${state.goal}\n\n请按以下结构回答：1. 问题规范化；2. 疾病机制与待核验靶点；3. 中药单体候选及逐条证据；4. 证据等级与来源；5. 数据缺口和风险；6. 下一步验证。必须区分数据库/原始文献支持、网络检索线索和模型假设。不得虚构 PMID、DOI、数据库记录、ADMET 或对接分数。没有真实同协议计算数据时，明确说明不能进行双排序。该输出用于科研教学，不构成诊疗建议。`;
 state.analysis.loading=true;state.analysis.error='';save();render();
 const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),100000);
 try{const res=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({messages:[{role:'user',content:prompt}],user_id:state.chat.userId}),signal:controller.signal});let data={};try{data=await res.json();}catch{}if(!res.ok||typeof data.reply!=='string'||!data.reply.trim())throw new Error(typeof data.error==='string'?data.error:`请求失败（${res.status}）`);state.analysis.reply=data.reply;state.analysis.submittedAt=new Date().toLocaleString('zh-CN');state.chat.messages=[...state.chat.messages.slice(-36),{role:'user',content:demand},{role:'assistant',content:data.reply}];state.chat.draft='';save();location.hash='evidence';}
 catch(err){state.analysis.error=err.name==='AbortError'?'分析请求超时，请重试。':(err.message||'暂时无法连接智能体，请稍后重试。');}
 finally{clearTimeout(timer);state.analysis.loading=false;save();render();}
}
function render(){const p=page();const navNotes=isCase()?['明确案例问题','核对样例文献','最匹配 / 非热门','写下验证方案','记录观察与结论']:['明确疾病与目标','核对来源与证据','检查数据是否可排名','记录验证方案','整理结果与报告'];document.querySelector('#nav').innerHTML=steps.map(([key,i,label],n)=>`<a href="#${key}" class="${p===key||(p==='compare'&&key==='ranking')?'active':''}" ${p===key?'aria-current="step"':''}>${icon(i)}<span class="nav-copy"><strong>${label}</strong><small>${navNotes[n]}</small></span><span class="step">0${n+1}</span></a>`).join('');const views={task:taskView,compare:isCase()?compareView:genericEvidenceView,ranking:isCase()?rankingView:genericRankingView,evidence:isCase()?evidenceView:genericEvidenceView,experiment:experimentView,report:resultView};document.querySelector('#main').innerHTML=views[p]();document.querySelector('#assistant').innerHTML=assistantView(p);const context=isCase()?'案例 01 / 肺癌 EGFR':'通用疾病分析';document.querySelector('#courseContext').textContent=context;document.querySelector('#contextLabel').textContent='/ '+context;if(window.lucide)lucide.createIcons();for(const id of ['chatDraft','clearChat','reset','askAgent']){const el=document.getElementById(id);if(el)el.disabled=!!state.chat.loading;}const log=document.getElementById('chatMessages');if(log)log.scrollTop=log.scrollHeight;}
document.addEventListener('click',async e=>{const next=e.target.closest('[data-next]');if(next)location.hash=next.dataset.next;
 if(!state.chat.loading&&e.target.closest('#reset')&&confirm('清除当前浏览器中的研究需求、笔记和报告草稿？')){const link=state.agentUrl;state={...initial(),agentUrl:link};save();location.hash='task';render();toast('当前草稿已重置');}
 if(e.target.closest('#useGeneral')){state.mode='general';state.demand='';save();location.hash='task';render();}
 if(e.target.closest('#loadCase')||e.target.closest('#openCase')){state.mode='case';state.demand='比较肺癌 EGFR 相关的中药单体，查看文献证据与两条候选排序路径。';save();location.hash=e.target.closest('#openCase')&&page()==='ranking'?'ranking':'task';render();}
 if(e.target.closest('#startAnalysis'))runAnalysis();
 if(e.target.closest('#copyPrompt')){const prompt=document.querySelector('#samplePrompt').textContent.trim();try{await navigator.clipboard.writeText(prompt);toast('问题已复制');}catch{window.prompt('请复制这段问题：',prompt);}}
 if(!state.chat.loading&&e.target.closest('#askAgent')){state.chat.draft=document.querySelector('#samplePrompt')?.textContent.trim()||'';render();document.querySelector('#chatDraft')?.focus();}
 if(e.target.closest('#sendChat'))sendChat();
 if(e.target.closest('#retryChat'))sendChat();
 if(!state.chat.loading&&e.target.closest('#clearChat')){state.chat.messages=[];state.chat.error='';state.chat.draft='';save();render();document.querySelector('#chatDraft')?.focus();}
 if(e.target.closest('#download')){const url=URL.createObjectURL(new Blob(['\ufeff'+completeReportText()],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=isCase()?'肺癌EGFR候选比较教学报告.txt':'启真问智通用疾病研究报告.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('报告已导出');}
});
document.addEventListener('input',e=>{const el=e.target;if(el.dataset.note)state.notes[el.dataset.note]=el.value;else if(el.dataset.experiment)state.experiment[el.dataset.experiment]=el.value;else if(el.dataset.result)state.result[el.dataset.result]=el.value;else if(el.id==='demand')state.demand=el.value;else if(el.id==='target')state.target=el.value;else if(el.id==='scope')state.scope=el.value;else if(el.id==='analysisCandidate')state.analysisCandidate=el.value;else if(el.id==='reason')state.reason=el.value;else if(el.id==='agentUrl')state.agentUrl=el.value;else if(el.id==='chatDraft'){state.chat.draft=el.value;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}catch{}}else return;save();});
document.addEventListener('keydown',e=>{if(e.target.id==='chatDraft'&&e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();sendChat();}});
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.reviewed){state.reviewed[el.dataset.reviewed]=el.checked;save();}if(el.id==='selected'){state.selected=el.value;save();render();}if(el.id==='goal'){state.goal=el.value;save();}});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});render();checkHealth();
