/* 双排序界面：只呈现确定性程序结果，导入记录并不等于科学核验。 */
let rankData=structuredClone(HerbRankingData),rankParams={...HerbRanking.DEFAULTS},rankNotice='';
try{const stored=JSON.parse(localStorage.getItem('herblab-ranking-v1'));if(stored){HerbRanking.compute(stored.data,stored.parameters);rankData=stored.data;rankParams=stored.parameters;}}catch{rankNotice='上次保存的排序数据无法读取，已恢复原始资料。';}
const number=v=>v==null?'—':v.toFixed(2);
function rankSave(){try{localStorage.setItem('herblab-ranking-v1',JSON.stringify({data:rankData,parameters:rankParams}));}catch{rankNotice='浏览器保存空间不足，请导出计算记录保存。';}}
function rankDownload(name,data){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function rankSummary(){const r=HerbRanking.compute(rankData,rankParams);return `双排序：规则 ${r.engineVersion}，数据 ${rankData.metadata.version}；${r.eligible}/${r.total} 条进入共同队列。\n参数：${JSON.stringify(r.parameters)}\n常规：${r.conventional.map(x=>`${x.rank}. ${x.name} ${number(x.base)}`).join('；')||'无可排序候选'}\n冷门：${r.cold.map(x=>`${x.rank}. ${x.name} ${number(x.cold)}`).join('；')||'无可排序候选'}\n这是待验证的教学排序规则，不代表疗效、结合亲和力或已发现新药。未入队列：${r.rows.filter(x=>!x.eligible).map(x=>`${x.name}：${x.status} ${x.missing.join('、')}`).join('；')}`;}
function rankTable(rows,cold){return rows.length?`<div class="table-scroll"><table><thead><tr><th>名次</th><th>候选</th><th>基础分</th><th>${cold?'冷门分':'热度'}</th>${cold?'<th>加分</th><th>名次变化</th>':''}</tr></thead><tbody>${rows.map(c=>`<tr><td>${c.rank}</td><td>${esc(c.name)}<small>${esc(c.id)}</small></td><td>${number(c.base)}</td><td>${cold?number(c.cold):c.heat}</td>${cold?`<td>+${number(c.boost)}</td><td>${c.delta>0?'↑'+c.delta:c.delta<0?'↓'+(-c.delta):'持平'}</td>`:''}</tr>`).join('')}</tbody></table></div>`:'<div class="rank-empty">尚无可排序候选。补齐下方所列数据后，程序会自动计算。</div>';}
function rankingView(){const r=HerbRanking.compute(rankData,rankParams),m=rankData.metadata;const sensitivity=new Map([0,5,10,20].map(b=>[b,new Map(HerbRanking.compute(rankData,{...rankParams,bonus:b}).cold.map(x=>[x.id,x.rank]))]));const originals=new Map(rankData.candidates.map(x=>[x.id,x]));
return heading('REPRODUCIBLE RANKING / 常规与冷门','同一批候选，两种排序视角','先检查数据与过滤条件，再比较基础分和低热度加分。')+`
${rankNotice?`<div class="rank-notice" role="status">${esc(rankNotice)}</div>`:''}
<section class="section"><div class="section-head"><h2>当前数据</h2><span class="pill warn">规则草案 · 待验证</span></div><p>${esc(m.description||'用户导入数据，来源与科学质量仍需复核。')}</p><p class="mini-note">靶点：${esc(m.target)}<br>数据版本：${esc(m.version)} · 规则版本：${r.engineVersion}<br>程序检查字段完整性与协议一致性，不会自动证明来源真实或结论正确。</p><div class="stats"><div class="stat"><span>候选总数</span><strong>${r.total}</strong></div><div class="stat green"><span>可进入双排名</span><strong>${r.eligible}</strong></div><div class="stat"><span>待补或被排除</span><strong>${r.total-r.eligible}</strong></div></div><div class="button-row rank-tools"><button id="rankTemplate">下载当前数据模板</button><label class="rank-import">导入补齐的 JSON<input type="file" id="rankImport" accept=".json,application/json"></label><button id="rankExport">导出计算记录</button><button id="rankReset">恢复原始三条资料</button></div><p class="mini-note">模板保留已知资料；补齐后导入。计算记录包含原始输入、参数、两个排名、缺失原因和时间，可复算。导入仅保存在本机浏览器。</p></section>
<section class="section"><div class="section-head"><h2>排序规则</h2></div><p>常规排名按基础分从高到低；冷门排名在相同候选队列上增加有限的低热度加分。硬过滤未通过、记录缺失或基础分不足的候选不进入任一排名。</p><div class="rank-form">${[['strong','强锚点（对接分数）'],['weak','弱锚点（对接分数）'],['minBase','基础分最低门槛'],['bonus','冷门加分上限（0–20）']].map(([key,label])=>`<label>${label}<input id="rank-${key}" type="number" step="any" value="${rankParams[key]}"></label>`).join('')}</div><button id="rankApply" class="primary">应用参数并重算</button><details class="rank-details"><summary>查看公式、分箱和适用边界</summary><p>基础分 = clamp((弱锚点 − 对接分数) ÷ (弱锚点 − 强锚点) × 100, 0, 100)。只适用于同一协议下“越低越优”的对接分数；锚点需要结合真实协议校准。默认 −12、−4、门槛 50 是工程草案。</p><p>热度为 0、1–9、10–99、100–999、≥1000 时，新颖度系数依次为 1、0.75、0.5、0.25、0。冷门分 = 基础分 + 加分上限 × 新颖度系数，可超过 100。低热度不等于科学创新。</p><p>并列分数并列名次（1、1、3），同分按候选编号稳定显示。名次变化 = 常规名次 − 冷门名次。分数计算使用完整精度，表格显示两位小数。样例文献数量不能当作热度；未检索不能当作 0。</p><p>这套公式是对原方案“双排序”需求的可执行草案，原文件没有规定这些数值。它不代表实验结合力、临床疗效或经验证的药物发现模型。</p></details></section>
<div class="rank-panels"><section class="section"><div class="section-head"><h2>常规排名</h2><span class="pill neutral">基础分</span></div>${rankTable(r.conventional,false)}</section><section class="section"><div class="section-head"><h2>冷门排名</h2><span class="pill neutral">基础分 + 加分</span></div>${rankTable(r.cold,true)}</section></div>
${r.eligible?`<section class="section"><div class="section-head"><h2>加分幅度会怎样影响排名？</h2></div><div class="table-scroll"><table><thead><tr><th>候选</th>${[0,5,10,20].map(b=>`<th>上限 ${b}</th>`).join('')}</tr></thead><tbody>${r.conventional.map(c=>`<tr><td>${esc(c.name)}</td>${[0,5,10,20].map(b=>`<td>${sensitivity.get(b).get(c.id)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="mini-note">队列与其他参数保持不变，只改变冷门加分。排名对加分敏感时，需要解释参数选择，不能只展示最有利的一组。</p></section>`:''}
<section class="section"><div class="section-head"><h2>数据缺口与逐条依据</h2></div>${r.rows.map(c=>{const source=originals.get(c.id);return `<details class="rank-details" ${!c.eligible?'open':''}><summary>${esc(c.name)} · ${esc(c.status)}</summary><p><strong>基础分：</strong>${number(c.base)}　<strong>热度：</strong>${c.heat??'待检索'}　<strong>新颖度系数：</strong>${number(c.novelty)}</p>${c.missing.length?`<p class="rank-missing">待补：${c.missing.map(esc).join('；')}。</p>`:''}${c.reason?`<p>过滤说明：${esc(c.reason)}</p>`:''}<p>证据：${esc(c.evidence)}</p><p>风险：${esc(c.risk)}</p><details><summary>原始输入与出处</summary><pre class="rank-source">${esc(JSON.stringify(source,null,2))}</pre></details></details>`;}).join('')}</section>
${actions('计算记录可以复核，不替代实验验证','evidence','结合文献解读排名')}`;}
document.addEventListener('click',e=>{
 if(e.target.closest('#rankApply')){try{const p={};for(const k of Object.keys(HerbRanking.DEFAULTS)){const value=document.getElementById('rank-'+k).value;if(!value.trim())throw new Error('参数不能为空。');p[k]=Number(value);}HerbRanking.compute(rankData,p);rankParams=p;rankNotice='已使用当前参数重新计算。';rankSave();render();}catch(err){rankNotice=err.message;toast(err.message);}}
 if(e.target.closest('#rankTemplate'))rankDownload('双排序待补数据.json',rankData);
 if(e.target.closest('#rankExport'))rankDownload('双排序计算记录.json',{exportedAt:new Date().toISOString(),warning:'教学排序规则草案，未作科学有效性验证',data:rankData,parameters:rankParams,result:HerbRanking.compute(rankData,rankParams)});
 if(e.target.closest('#rankReset')&&confirm('恢复原始三条资料和默认参数？当前导入数据会被替换，请先导出保存。')){rankData=structuredClone(HerbRankingData);rankParams={...HerbRanking.DEFAULTS};rankNotice='已恢复原始真实资料；未填写任何模拟对接分数。';rankSave();render();}
});
document.addEventListener('change',async e=>{if(e.target.id!=='rankImport')return;const f=e.target.files[0];if(!f)return;try{if(f.size>5*1024*1024)throw new Error('文件不能超过 5 MB。');const parsed=JSON.parse((await f.text()).replace(/^\uFEFF/,''));const data=parsed.data||parsed;const parameters=parsed.data?HerbRanking.settings(parsed.parameters||rankParams):rankParams;HerbRanking.compute(data,parameters);rankData=data;rankParams=parameters;rankNotice='数据已导入并计算。请核对来源、过滤规则及对接协议；导入不等于已科学核验。';rankSave();render();}catch(err){rankNotice='导入未生效：'+err.message;render();}});
