/* 双排序界面：只呈现确定性程序结果，导入记录并不等于科学核验。 */
let rankData=structuredClone(HerbRankingData),rankParams={...HerbRanking.DEFAULTS,...(HerbRankingData.recommendedParameters||{})},rankNotice='';
try{const stored=JSON.parse(localStorage.getItem('herblab-ranking-v1'));if(stored){const normalized=HerbRanking.settings(stored.parameters||{});HerbRanking.compute(stored.data,normalized);if(stored.data.metadata.version==='egfr-teaching-2026-09-26-v1'){rankNotice='已载入新完成的 2ITW 对接教学数据。原始旧版仍可从备份文件导入。';}else{rankData=stored.data;rankParams=normalized;}}}catch{rankNotice='上次保存的排序数据无法读取，已恢复原始资料。';}
const number=v=>v==null?'—':(Math.abs(v)<.001&&v!==0?v.toExponential(3):v.toFixed(2));
const precise=v=>v==null?'—':(Math.abs(v)<.001&&v!==0?v.toExponential(3):v.toFixed(4));
function rankSave(){try{localStorage.setItem('herblab-ranking-v1',JSON.stringify({data:rankData,parameters:rankParams}));}catch{rankNotice='浏览器保存空间不足，请导出计算记录保存。';}}
function rankDownload(name,data){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function rankSummary(){const r=HerbRanking.compute(rankData,rankParams),ref=r.reference||{};return `双排序：规则 ${r.engineVersion}，数据 ${rankData.metadata.version}；常规 ${r.conventionalEligible??r.conventional.length}/${r.total} 条，非热门 ${r.eligible}/${r.total} 条。\n参数：${JSON.stringify(r.parameters)}\n热度公式：q=(n+α)/(Σn+αN)，I=−log2(q)，新颖度=(I−minI)/(maxI−minI)；α=${r.parameters.smoothing}。\n常规：${r.conventional.map(x=>`${x.rank}. ${x.name} ${number(x.base)}`).join('；')||'无可排序候选'}\n非热门：${r.cold.map(x=>`${x.rank}. ${x.name} ${number(x.cold)}`).join('；')||'无可排序候选'}\n参考队列 ${ref.poolSize??0} 条、总报告数 ${ref.totalReports??0}；这是当前候选队列的参考分布，不代表疗效，也不是全体文献的信息熵。未入队列：${r.rows.filter(x=>!x.matchEligible).map(x=>`${x.name}：${x.status} ${x.missing.join('、')}`).join('；')}`;}
function rankTable(rows,cold){return rows.length?`<div class="table-scroll"><table><thead><tr><th>名次</th><th>候选</th><th>匹配分</th><th>热度</th>${cold?'<th>q</th><th>惊奇度 I</th><th>新颖度</th><th>加分</th><th>最终分</th><th>名次变化</th>':'<th>匹配来源 / 方法</th>'}</tr></thead><tbody>${rows.map(c=>`<tr><td>${c.rank}</td><td>${esc(c.name)}<small>${esc(c.id)}</small></td><td>${number(c.base)}</td><td>${c.heat==null?'未知':c.heat}</td>${cold?`<td>${precise(c.heatProbability)}</td><td>${number(c.surprisal)}</td><td>${number(c.novelty)}</td><td>+${number(c.boost)}</td><td>${number(c.cold)}</td><td>${c.delta>0?'↑'+c.delta:c.delta<0?'↓'+(-c.delta):'持平'}</td>`:`<td>${esc(c.matchMethod||'—')} · ${esc(c.matchSource||'—')}</td>`}</tr>`).join('')}</tbody></table></div>`:'<div class="rank-empty">尚无可排序候选。补齐下方所列数据后，程序会自动计算。</div>';}
function rankingView(){const r=HerbRanking.compute(rankData,rankParams),m=rankData.metadata;const sensitivity=new Map([0,5,10,20].map(b=>[b,new Map(HerbRanking.compute(rankData,{...rankParams,bonus:b}).cold.map(x=>[x.id,x.rank]))]));const originals=new Map(rankData.candidates.map(x=>[x.id,x]));
return heading('03 / 候选排名',`${esc(m.target||'当前数据集')} · 两条筛选路径`,'第一榜看匹配程度，第二榜加入非热门参考；都需要结合文献与实验核验。')+`
${window.ResearchUI&&ResearchUI.hasResult()?`<div class="research-ranking-boundary"><strong>本轮研究候选线索</strong><p>以下候选仍需身份、相关性和数据协议核验；本页双排序只对当前导入数据集计算。</p>${ResearchUI.candidatePanel()}</div>`:''}<div class="flow-notice">当前数据集：${esc(m.target||'未命名靶点')}。最匹配与非热门是两种教学视角；新检索疾病的线索不会自动套用本数据集的靶点或排名。</div><div class="path-grid"><button class="path-card" data-scroll="matched-list"><span class="path-no">第一榜</span><h2>匹配程度</h2><p>按匹配分排序。匹配分可以来自显式评分、结构化组件或同协议对接代理分；热度未知也不影响本榜。</p><strong>${r.conventional[0]?esc(r.conventional[0].name):'暂无可排序候选'} ${icon('arrow-down-right')}</strong></button><button class="path-card alt" data-scroll="uncommon-list"><span class="path-no">第二榜</span><h2>匹配 + 非热门参考</h2><p>只在匹配合格且热度已知的共同队列中，按平滑后的热度概率、新颖度参考和加分排序。</p><strong>${r.cold[0]?esc(r.cold[0].name):'暂无可排序候选'} ${icon('arrow-down-right')}</strong></button></div>
<section class="section"><div class="section-head"><h2>当前数据集候选</h2><small>${r.total} 条记录</small></div><div class="candidate-grid">${r.rows.map(row=>{const c=originals.get(row.id),pmid=c?.pmid;return `<article class="candidate-card"><span class="pill ${row.matchEligible?'':'warn'}">${row.matchEligible?(row.eligible?'进入两榜共同队列':'仅进入第一榜'):'待补或排除'}</span><h3>${esc(row.name)}</h3><p>${esc(row.id)} · PubChem CID ${esc(c?.cid||'待核对')}</p><small>匹配分 ${number(row.base)} · 文献热度 ${row.heat==null?'未知':row.heat}</small>${pmid?`<a href="https://pubmed.ncbi.nlm.nih.gov/${encodeURIComponent(pmid)}/" target="_blank" rel="noopener noreferrer">核对样例文献 ${icon('arrow-up-right')}</a>`:'<span class="mini-note">暂无可核对的 PubMed 编号</span>'}</article>`}).join('')}</div></section>
${rankNotice?`<div class="rank-notice" role="status">${esc(rankNotice)}</div>`:''}
<section class="section"><div class="section-head"><h2>当前数据</h2><span class="pill warn">规则草案 · 待验证</span></div><p>${esc(m.description||'用户导入数据，来源与科学质量仍需复核。')}</p><p class="mini-note">靶点：${esc(m.target)}<br>数据版本：${esc(m.version)} · 规则版本：${r.engineVersion}<br>程序检查字段完整性与协议一致性，不会自动证明来源真实或结论正确。</p><div class="stats"><div class="stat"><span>候选总数</span><strong>${r.total}</strong></div><div class="stat green"><span>第一榜匹配合格</span><strong>${r.conventionalEligible??r.conventional.length}</strong></div><div class="stat"><span>第二榜热度已知</span><strong>${r.eligible}</strong></div></div><div class="button-row rank-tools"><button id="rankTemplate">下载当前数据模板</button><label class="rank-import">导入补齐的 JSON<input type="file" id="rankImport" accept=".json,application/json"></label><button id="rankExport">导出计算记录</button><button id="rankReset">恢复当前数据集</button></div><p class="mini-note">模板保留已知资料，并将匹配分、热度与可选组件标为待补；补齐后导入。计算记录包含原始输入、参数、两个排名、缺失原因和时间，可复算。导入仅保存在本机浏览器。</p></section>
<section class="section"><div class="section-head"><h2>排序规则</h2></div><p>第一榜按匹配分从高到低，匹配合格但热度未知的候选仍可进入；第二榜只使用热度已知的共同队列。硬过滤未通过、匹配机制数据缺失或基础分不足的候选不进入第一榜。</p><div class="rank-form">${[['strong','强锚点（对接代理）'],['weak','弱锚点（对接代理）'],['minBase','基础分最低门槛'],['bonus','非热门加分上限（0–20）'],['smoothing','平滑项 α（>0）']].map(([key,label])=>`<label>${label}<input id="rank-${key}" type="number" step="any" value="${rankParams[key]??''}"></label>`).join('')}</div><button id="rankApply" class="primary">应用参数并重算</button><details class="rank-details"><summary>查看公式、匹配来源和适用边界</summary><p>显式匹配分来自用户提供的 0–100 分；结构化组件模式要求 structure、channel、affinity 三项都有数值和来源，按当前数据集声明的权重合成；未提供显式匹配对象时可使用同协议对接代理分；显式匹配资料不完整时保持待补。组件分需要有记录的归一化方法，缺一项不会按 0 补。</p><p>对热度已知的共同队列，q=(n+α)/(Σn+αN)，I=−log2(q)，新颖度=(I−minI)/(maxI−minI)；α=${rankParams.smoothing}。单一候选或等计数时新颖度为 0。非热门最终分 = 匹配分 + 加分上限 × 新颖度。第二榜参考的是当前候选队列的文献计数分布，计数会受名称、别名和检索覆盖偏差影响，不是疗效、真实流行度或全体文献的信息熵。</p><p>第二榜的名次变化以该榜共同队列内的原始匹配名次为基准；第一榜可能包含更多热度未知候选。文献热度未知不会影响第一榜，但会排除出第二榜。</p><p>并列分数并列名次，同分按候选编号稳定显示。分数计算使用完整精度，表格只作展示四舍五入。以上是规则草案，不代表实验结合力、临床疗效或经验证的药物发现模型。</p></details></section>
<div class="rank-panels"><section class="section" id="matched-list"><div class="section-head"><h2>第一榜 · 匹配程度</h2><span class="pill neutral">匹配分（${r.conventionalEligible??r.conventional.length} 条）</span></div>${rankTable(r.conventional,false)}</section><section class="section" id="uncommon-list"><div class="section-head"><h2>第二榜 · 匹配 + 非热门参考</h2><span class="pill neutral">共同热度队列（${r.eligible} 条）</span></div>${rankTable(r.cold,true)}</section></div>
${r.eligible?`<section class="section"><div class="section-head"><h2>加分幅度会怎样影响第二榜？</h2></div><div class="table-scroll"><table><thead><tr><th>候选</th>${[0,5,10,20].map(b=>`<th>上限 ${b}</th>`).join('')}</tr></thead><tbody>${r.cold.map(c=>`<tr><td>${esc(c.name)}</td>${[0,5,10,20].map(b=>`<td>${sensitivity.get(b).get(c.id)??'—'}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="mini-note">只改变非热门加分上限；第一榜和第二榜的队列规则保持不变。</p></section>`:''}
<section class="section"><div class="section-head"><h2>数据缺口与逐条依据</h2></div>${r.rows.map(c=>{const source=originals.get(c.id),components=source?.match?.components,weights=c.componentInfo?.weights||r.matchingWeights;return `<details class="rank-details" ${!c.matchEligible?'open':''}><summary>${esc(c.name)} · ${esc(c.status)}</summary><p><strong>匹配分：</strong>${number(c.base)}　<strong>方法：</strong>${esc(c.matchMethod||'待计算')}　<strong>来源：</strong>${esc(c.matchSource||'待补')}</p><p><strong>第一榜热度：</strong>${c.heat==null?'未知（不影响第一榜）':c.heat}　<strong>第二榜 q：</strong>${precise(c.heatProbability)}　<strong>惊奇度 I：</strong>${precise(c.surprisal)}　<strong>新颖度参考：</strong>${number(c.novelty)}</p>${components?`<p><strong>结构化组件：</strong>结构 ${esc(components.structure?.value??'—')}（${esc(components.structure?.source||'无来源')}），通道 ${esc(components.channel?.value??'—')}（${esc(components.channel?.source||'无来源')}），亲和 ${esc(components.affinity?.value??'—')}（${esc(components.affinity?.source||'无来源')}）；权重 ${esc(JSON.stringify(weights||{}))}</p>`:''}${c.missing.length?`<p class="rank-missing">待补或待计算：${c.missing.map(esc).join('；')}。</p>`:''}${c.reason?`<p>过滤说明：${esc(c.reason)}</p>`:''}<p>证据：${esc(c.evidence)}</p><p>风险：${esc(c.risk)}</p><details><summary>原始输入与出处</summary><pre class="rank-source">${esc(JSON.stringify(source,null,2))}</pre></details></details>`;}).join('')}</section>
${actions('计算记录可以复核，不替代实验验证','experiment','进入湿实验设计')}`;}
document.addEventListener('click',e=>{
 const target=e.target.closest('[data-scroll]');if(target)document.getElementById(target.dataset.scroll)?.scrollIntoView({behavior:'smooth',block:'start'});
 if(e.target.closest('#rankApply')){try{const p={};for(const k of Object.keys(HerbRanking.DEFAULTS)){const value=document.getElementById('rank-'+k).value;if(!value.trim())throw new Error('参数不能为空。');p[k]=Number(value);}HerbRanking.compute(rankData,p);rankParams=p;rankNotice='已使用当前参数重新计算。';rankSave();render();}catch(err){rankNotice=err.message;toast(err.message);}}
 if(e.target.closest('#rankTemplate')){const template=structuredClone(rankData);template.metadata.matchPolicy ||= 'teacher-match-rubric-v1';template.candidates=template.candidates.map(c=>({...c,match:c.match?{...c.match,target:template.metadata.target,policy:template.metadata.matchPolicy,score:null,components:c.match.components||{structure:{value:null,source:''},channel:{value:null,source:''},affinity:{value:null,source:''}}}:{score:null,source:'',target:template.metadata.target,policy:template.metadata.matchPolicy,components:{structure:{value:null,source:''},channel:{value:null,source:''},affinity:{value:null,source:''}}},heat:c.heat?{...c.heat,count:null,query:c.heat.query||'',source:c.heat.source||''}:{count:null,query:'',source:''}}));rankDownload('双排序待补数据.json',template);}
 if(e.target.closest('#rankExport')){const result=HerbRanking.compute(rankData,rankParams);rankDownload('双排序计算记录.json',{exportedAt:new Date().toISOString(),warning:'教学排序规则草案，未作科学有效性验证',rawInputs:rankData,parameters:rankParams,engineVersion:result.engineVersion,reference:result.reference,result});}
 if(e.target.closest('#rankReset')&&confirm('恢复当前三条核验资料和默认参数？当前导入数据会被替换，请先导出保存。')){rankData=structuredClone(HerbRankingData);rankParams={...HerbRanking.DEFAULTS,...(HerbRankingData.recommendedParameters||{})};rankNotice='已恢复当前 2ITW 教学数据；请核对筛查范围与未校准的排序参数。';rankSave();render();}
});
document.addEventListener('change',async e=>{if(e.target.id!=='rankImport')return;const f=e.target.files[0];if(!f)return;try{if(f.size>5*1024*1024)throw new Error('文件不能超过 5 MB。');const parsed=JSON.parse((await f.text()).replace(/^\uFEFF/,''));const data=parsed.data||parsed;const parameters=parsed.data?HerbRanking.settings(parsed.parameters||rankParams):rankParams;HerbRanking.compute(data,parameters);rankData=data;rankParams=parameters;rankNotice='数据已导入并计算。请核对来源、过滤规则及对接协议；导入不等于已科学核验。';rankSave();render();}catch(err){rankNotice='导入未生效：'+err.message;render();}});
