/* 结构、通道、亲和力匹配排名；热度只作上下文，不参与评分。 */
const RANK_PARAMETER_LABELS={strong:'强锚点（对接代理）',weak:'弱锚点（对接代理）',minBase:'匹配分最低门槛'};
const rankDefaults=()=>Object.fromEntries(Object.keys(HerbRanking.DEFAULTS).map(k=>[k,HerbRanking.DEFAULTS[k]]));
const rankParameters=input=>{const p=rankDefaults();for(const key of Object.keys(p)){if(input&&Object.prototype.hasOwnProperty.call(input,key))p[key]=Number(input[key]);}return p;};
let rankData=structuredClone(HerbRankingData),rankParams=rankParameters({...HerbRankingData.recommendedParameters}),rankNotice='';
try{const stored=JSON.parse(localStorage.getItem('herblab-ranking-v1'));if(stored?.data){const p=rankParameters(stored.parameters);HerbRanking.compute(stored.data,p);rankData=stored.data;rankParams=p;}}catch{rankNotice='上次保存的排序数据无法读取，已恢复原始资料。';}
const number=v=>v==null?'—':(Number.isFinite(v)?(Math.abs(v)<.001&&v!==0?v.toExponential(3):v.toFixed(2)):'—');
function rankSave(){try{localStorage.setItem('herblab-ranking-v1',JSON.stringify({data:rankData,parameters:rankParams}));}catch{rankNotice='浏览器保存空间不足，请导出计算记录保存。';}}
function rankDownload(name,data){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function rankSummary(){const r=HerbRanking.compute(rankData,rankParams);return `匹配排名：规则 ${r.engineVersion}，数据 ${rankData.metadata.version}；${r.conventionalEligible??r.conventional.length}/${r.total} 条进入排名。\n参数：${JSON.stringify(r.parameters)}\n排名：${r.conventional.map(x=>`${x.rank}. ${x.name} ${number(x.base)}`).join('；')||'无可排序候选'}\n未入排名：${r.rows.filter(x=>!x.matchEligible).map(x=>`${x.name}：${x.status} ${(x.matchMissing||x.missing||[]).join('、')}`).join('；')||'无'}\n文献热度仅作背景信息，未参与匹配分。`;}
function rankTable(rows){return rows.length?`<div class="table-scroll"><table><thead><tr><th>名次</th><th>候选</th><th>匹配分</th><th>匹配方法</th><th>来源</th><th>状态</th></tr></thead><tbody>${rows.map(c=>`<tr><td>${c.rank}</td><td>${esc(c.name)}<small>${esc(c.id)}</small></td><td>${number(c.base)}</td><td>${esc(c.matchMethod||'—')}</td><td>${esc(c.source||c.matchSource||'—')}</td><td>${esc(c.status||'可排序')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="rank-empty">尚无可排序候选。补齐结构、通道、亲和力匹配资料后，程序会自动计算。</div>';}
function rankingView(){const r=HerbRanking.compute(rankData,rankParams),m=rankData.metadata,originals=new Map(rankData.candidates.map(x=>[x.id,x]));
 return heading('03 / 候选匹配排名',`${esc(m.target||'当前数据集')} · 结构 / 通道 / 亲和力`,'排名只反映当前数据集内的可复核匹配计算；真实计算结果需要由相应结构、通道与亲和力方法提供。')+
 `${window.ResearchUI&&ResearchUI.hasResult()?`<div class="research-ranking-boundary"><strong>本轮研究候选线索</strong><p>研究面板独立于排名；候选进入排名前仍需核对身份、靶点和数据协议。</p>${ResearchUI.candidatePanel()}</div>`:''}<div class="flow-notice">当前目标：${esc(m.target||'未命名靶点')}。本页不会生成结构、通道或亲和力结果；评分方法必须来自真实计算或有来源的导入记录。${m.protocol?` 当前对接协议：${esc(m.protocol)}（仅作为匹配代理，已明确标注）。`:''}</div>
 <section class="section"><div class="section-head"><h2>当前候选</h2><small>${r.total} 条记录</small></div><div class="candidate-grid">${r.rows.map(row=>{const c=originals.get(row.id),heat=c?.heat?.count;return `<article class="candidate-card"><span class="pill ${row.matchEligible?'':'warn'}">${row.matchEligible?'进入匹配排名':'待补或排除'}</span><h3>${esc(row.name)}</h3><p>${esc(row.id)} · PubChem CID ${esc(c?.cid||'待核对')}</p><small>匹配分 ${number(row.base)} · 文献热度 ${heat==null?'未知（仅背景）':heat}</small>${c?.pmid?`<a href="https://pubmed.ncbi.nlm.nih.gov/${encodeURIComponent(c.pmid)}/" target="_blank" rel="noopener noreferrer">核对样例文献 ${icon('arrow-up-right')}</a>`:'<span class="mini-note">文献热度不参与排序</span>'}</article>`}).join('')}</div></section>
 ${rankNotice?`<div class="rank-notice" role="status">${esc(rankNotice)}</div>`:''}<section class="section"><div class="section-head"><h2>当前数据</h2><span class="pill warn">计算方法需真实数据</span></div><p>${esc(m.description||'用户导入数据，来源与科学质量仍需复核。')}</p><p class="mini-note">目标：${esc(m.target)}<br>数据版本：${esc(m.version)} · 规则版本：${esc(r.engineVersion)}<br>结构、通道、亲和力匹配权重：${esc(JSON.stringify(r.matchingWeights||m.matchingWeights||{}))}<br>程序检查字段完整性与协议一致性，不会自动生成计算结果。</p><div class="stats"><div class="stat"><span>候选总数</span><strong>${r.total}</strong></div><div class="stat green"><span>匹配合格</span><strong>${r.conventionalEligible??r.conventional.length}</strong></div><div class="stat"><span>待补或排除</span><strong>${r.rows.filter(x=>!x.matchEligible).length}</strong></div></div><div class="button-row rank-tools"><button id="rankTemplate">下载当前数据模板</button><label class="rank-import">导入匹配数据 JSON<input type="file" id="rankImport" accept=".json,application/json"></label><button id="rankExport">导出计算记录</button><button id="rankReset">恢复当前数据集</button></div><p class="mini-note">模板保留已知资料，将匹配分和组件值保留为 null；导入后可复核重算。导出包含原始输入、参数、引擎版本、权重与排名结果，便于复现。</p></section>
 <section class="section"><div class="section-head"><h2>匹配参数</h2></div><p>参数只用于真实匹配方法已提供的分数或当前数据集明确声明的对接代理映射。调整参数不会生成结构、通道或亲和力计算。</p><div class="rank-form">${Object.keys(HerbRanking.DEFAULTS).map(key=>`<label>${esc(RANK_PARAMETER_LABELS[key]||key)}<input id="rank-${key}" type="number" step="any" value="${rankParams[key]??''}"></label>`).join('')}</div><button id="rankApply" class="primary">应用参数并重算</button><details class="rank-details"><summary>查看匹配方法和适用边界</summary><p>匹配分可以来自有来源的显式评分、结构化组件（structure、channel、affinity）或同协议对接代理分。组件权重来自数据集 metadata；缺少真实值、来源或协议一致性时保持待补，不按 0 补。</p><p>当前 EGFR 对接代理：${esc(m.target||'未指定目标')}，协议 ${esc(m.protocol||'未指定协议')}。它是匹配代理，不能替代实验亲和力、结合自由能或疗效验证。</p><p>文献热度 ${esc(m.heatDefinition||'未提供统一口径')} 仅作为候选背景信息，不参与排序，也不产生派生分。</p></details></section>
 <section class="section" id="matched-list"><div class="section-head"><h2>匹配排名</h2><span class="pill neutral">${r.conventionalEligible??r.conventional.length} 条</span></div>${rankTable(r.conventional)}</section>
 <section class="section"><div class="section-head"><h2>数据缺口与逐条依据</h2></div>${r.rows.map(c=>{const source=originals.get(c.id),components=source?.match?.components||c.componentInfo?.components;return `<details class="rank-details" ${!c.matchEligible?'open':''}><summary>${esc(c.name)} · ${esc(c.status)}</summary><p><strong>匹配分：</strong>${number(c.base)}　<strong>方法：</strong>${esc(c.matchMethod||'待计算')}　<strong>来源：</strong>${esc(c.source||c.matchSource||'待补')}</p>${components?`<p><strong>组件：</strong>${esc(JSON.stringify(components))}；权重 ${esc(JSON.stringify(c.componentInfo?.weights||r.matchingWeights||m.matchingWeights||{}))}</p>`:''}${(c.matchMissing||c.missing||[]).length?`<p class="rank-missing">待补或待计算：${(c.matchMissing||c.missing||[]).map(esc).join('；')}。</p>`:''}${c.reason?`<p>过滤说明：${esc(c.reason)}</p>`:''}<p>证据：${esc(c.evidence||source?.evidence||'未填写')}</p><p>风险：${esc(c.risk||source?.risk||'未填写')}</p><details><summary>原始输入与出处</summary><pre class="rank-source">${esc(JSON.stringify(source,null,2))}</pre></details></details>`;}).join('')}</section>${actions('计算记录可以复核，不替代实验验证','experiment','进入湿实验设计')}`;}
document.addEventListener('click',e=>{const target=e.target.closest('[data-scroll]');if(target)document.getElementById(target.dataset.scroll)?.scrollIntoView({behavior:'smooth',block:'start'});if(e.target.closest('#rankApply')){try{const p={};for(const key of Object.keys(HerbRanking.DEFAULTS)){const input=document.getElementById('rank-'+key);if(!input?.value.trim())throw new Error('参数不能为空。');p[key]=Number(input.value);}HerbRanking.compute(rankData,p);rankParams=rankParameters(p);rankNotice='已使用当前参数重新计算。';rankSave();render();}catch(err){rankNotice=err.message;toast(err.message);}}if(e.target.closest('#rankTemplate')){const template=structuredClone(rankData);template.metadata.matchPolicy ||= 'teacher-match-rubric-v1';template.metadata.matchWeights ||= [1/3,1/3,1/3];template.candidates=template.candidates.map(c=>({...c,match:c.match?{...c.match,target:template.metadata.target,policy:template.metadata.matchPolicy,score:null,components:c.match.components||{structure:{value:null,source:''},channel:{value:null,source:''},affinity:{value:null,source:''}}}:{score:null,source:'',target:template.metadata.target,policy:template.metadata.matchPolicy,components:{structure:{value:null,source:''},channel:{value:null,source:''},affinity:{value:null,source:''}}}}));rankDownload('匹配排名待补数据.json',template);}if(e.target.closest('#rankExport')){const result=HerbRanking.compute(rankData,rankParams);rankDownload('匹配排名计算记录.json',{exportedAt:new Date().toISOString(),warning:'匹配结果必须来自真实计算或有来源的导入记录',rawInputs:rankData,parameters:result.parameters,matchingWeights:result.matchingWeights,engineVersion:result.engineVersion,result});}if(e.target.closest('#rankReset')&&confirm('恢复当前数据集和默认参数？当前导入数据会被替换，请先导出保存。')){rankData=structuredClone(HerbRankingData);rankParams=rankParameters(HerbRankingData.recommendedParameters);rankNotice='已恢复当前数据集。';rankSave();render();}});
document.addEventListener('change',async e=>{if(e.target.id!=='rankImport')return;const f=e.target.files[0];if(!f)return;try{if(f.size>5*1024*1024)throw new Error('文件不能超过 5 MB。');const parsed=JSON.parse((await f.text()).replace(/^\uFEFF/,'')),data=parsed.rawInputs||parsed.data||parsed,p=rankParameters(parsed.rawInputs||parsed.data?parsed.parameters:rankParams);HerbRanking.compute(data,p);rankData=data;rankParams=p;rankNotice='数据已导入并计算。请核对来源、匹配方法及协议；导入不等于已科学核验。';rankSave();render();}catch(err){rankNotice='导入未生效：'+err.message;render();}});
