(function(){
  const KEY='herblab-research-v2';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const safeUrl=v=>{try{const u=new URL(String(v));return /^https?:$/.test(u.protocol)?u.href:''}catch{return ''}};
  const icon=name=>`<i data-lucide="${name}"></i>`;
  const initial={disease:'',target:'',compound:'',result:null,loading:false,error:'',lookup:{},review:{},history:[],filterType:'全部',loadingStage:0,elapsed:0};
  let s={...initial},activeController=null,loadingTimer=null,lookupQuery='',lookupData=null,lookupLoading=false;
  try{const x=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('herblab-research-v1'));if(x&&typeof x==='object')s={...s,...x}}catch{}
  s.loading=false;s.loadingStage=0;s.elapsed=0;s.review=s.review&&typeof s.review==='object'?s.review:{};
  s.history=Array.isArray(s.history)?s.history.slice(0,8):[];s.filterType=typeof s.filterType==='string'?s.filterType:'全部';
  s.lookup=Object.fromEntries(Object.entries(s.lookup||{}).filter(([,v])=>v&&!v.loading));
  if(s.result)s.result={...s.result,researchId:''};
  function save(){try{localStorage.setItem(KEY,JSON.stringify({...s,loading:false,loadingStage:0,elapsed:0}))}catch{}}

  function searchForm(){return `<section class="research-hero">
    <div class="research-hero-copy"><span class="eyebrow">NEW RESEARCH / 新建研究</span><h2>你想研究什么疾病？</h2><p>输入中文或英文疾病名称，系统将检索真实文献，并帮助你梳理可能的中药单体线索与证据边界。</p></div>
    <label class="research-primary-input"><span>疾病名称</span><input id="researchDisease" maxlength="120" value="${esc(s.disease)}" placeholder="例如：原发性高血压" autocomplete="off"></label>
    <div class="research-examples"><span>试试：</span>${['原发性高血压','三叉神经痛','类风湿关节炎'].map(x=>`<button type="button" data-example-disease="${esc(x)}">${esc(x)}</button>`).join('')}</div>
    <details class="research-advanced"><summary>高级条件（可选）</summary><div class="research-form"><label>指定靶点<input id="researchTarget" maxlength="120" value="${esc(s.target)}" placeholder="例如：SCN9A"></label><label>指定化合物（英文）<input id="researchCompound" maxlength="120" value="${esc(s.compound)}" placeholder="例如：Quercetin"></label></div></details>
    <div class="research-actions main-action"><button id="researchSearch" class="primary" ${s.loading?'disabled':''}>开始研究</button></div>
    ${s.error?`<p class="research-error" role="alert">${esc(s.error)}</p>`:''}
    <p class="research-trust">${icon('shield-check')}中文名称会先规范化为英文医学术语；检索来源和实际查询式会完整保留。</p>
  </section>${window.SourceUI?.panel()||''}${historyView()}`}
  function historyView(){if(!s.history.length)return '';return `<details class="research-history"><summary><span>${icon('folder-clock')}我的研究</span><strong>${s.history.length} 项</strong></summary><div class="history-list">${s.history.map(item=>`<article><div><strong>${esc(item.title||item.disease||'未命名研究')}</strong><span>${esc(item.disease||'')} · ${esc(item.savedAt||'')}</span></div><div><button data-history-open="${esc(item.id)}">继续查看</button><button data-history-rename="${esc(item.id)}">重命名</button></div></article>`).join('')}</div><p>历史记录保存在当前浏览器。重新打开旧结果后，需要再次检索才能将文献传给 AI。</p></details>`}
  function rememberResearch(data){const now=new Date(),item={id:`research-${Date.now()}-${Math.random().toString(16).slice(2,8)}`,title:`${data.disease?.label||s.disease}研究`,disease:data.disease?.label||s.disease,term:data.disease?.term||'',savedAt:now.toLocaleString('zh-CN'),input:{disease:s.disease,target:s.target,compound:s.compound},result:{...data,researchId:''}};s.history=[item,...s.history].slice(0,8)}
  function openHistory(id){const item=s.history.find(x=>x.id===id);if(!item)return;s.disease=item.input?.disease||item.disease||'';s.target=item.input?.target||'';s.compound=item.input?.compound||'';s.result={...item.result,researchId:''};s.error='';save();location.hash='evidence';window.render?.()}
  function renameHistory(id){const item=s.history.find(x=>x.id===id);if(!item)return;const value=window.prompt('为这项研究输入新名称：',item.title||item.disease||'');if(value&&value.trim()){item.title=value.trim().slice(0,80);save();window.render?.()}}
  function loadingView(){const labels=['识别并规范化疾病名称','连接 PubMed / Europe PMC','整理题录与摘要','提取待核验化学线索'];const stage=Math.min(s.loadingStage,labels.length-1);return `<section class="research-loading" aria-live="polite"><div class="loading-orbit">${icon('search')}</div><div><span class="eyebrow">正在建立本轮研究</span><h2>${esc(labels[stage])}</h2><ol>${labels.map((x,i)=>`<li class="${i<stage?'done':i===stage?'active':''}">${i<stage?icon('check'):icon('circle')}<span>${esc(x)}</span></li>`).join('')}</ol><p>已等待 ${s.elapsed} 秒，通常需要 10–30 秒。数据库响应速度可能波动。</p><button id="researchCancel">取消本次检索</button></div></section>`}
  function progress(){const r=s.result;const read=(r?.records||[]).filter(x=>s.review[x.pmid]?.reviewed).length;const c=window.HerbWorkspace?.currentCandidate?.();return `<section class="research-progress"><div class="section-head"><h2>本轮研究进度</h2><span class="pill neutral">${r?'已建立':'尚未开始'}</span></div><div class="research-step-grid"><div><strong>1 · 研究疾病</strong><span>${esc(r?.disease?.label||s.disease||'未填写')}</span></div><div><strong>2 · 文献证据</strong><span>${r?.records?.length||0} 篇结果 · ${read} 篇已加入笔记</span></div><div><strong>3 · 化学线索</strong><span>${r?.candidates?.length||0} 条待核验</span></div><div><strong>4 · 讨论对象</strong><span>${c?.origin==='research'?esc(c.name||'已选择'):'尚未选择'}</span></div></div></section>`;}
  const evidenceTypes=['未判定','细胞实验','动物实验','临床研究','计算预测','综述','其他'];
  function inferredType(x){const t=`${x.title||''} ${x.abstract||''}`.toLowerCase();if(/systematic review|meta-analysis|review of/.test(t))return '综述';if(/randomi[sz]ed|patients?|clinical trial|cohort/.test(t))return '临床研究';if(/mice|mouse|rats?|in vivo|animal/.test(t))return '动物实验';if(/cells?|in vitro|cell line/.test(t))return '细胞实验';if(/docking|network pharmacology|molecular dynamics|in silico/.test(t))return '计算预测';return '待判定';}
  function overview(r){const rows=r.records||[],types={};for(const x of rows){const k=inferredType(x);types[k]=(types[k]||0)+1}const typeText=Object.entries(types).map(([k,v])=>`${k} ${v}`).join(' · ')||'暂无可判定记录';const chemicals=(r.candidates||[]).slice(0,3).map(x=>x.name).filter(Boolean);return `<section class="research-overview"><div class="overview-title"><div><span class="eyebrow">RESEARCH OVERVIEW</span><h2>${esc(r.disease?.label||s.disease)} · 研究概览</h2></div><span class="result-count">${esc(r.total??rows.length)}<small>检索命中</small></span></div><div class="overview-grid"><div><span>本页展示</span><strong>${rows.length} 篇文献</strong><small>按数据库返回顺序</small></div><div><span>初步证据类型</span><strong>${esc(typeText)}</strong><small>根据题名与摘要自动提示，需人工确认</small></div><div><span>化学实体线索</span><strong>${chemicals.length?esc(chemicals.join('、')):'暂未提取到'}</strong><small>${(r.candidates||[]).length} 条机器线索，均未验证疗效</small></div></div><div class="boundary-note">${icon('info')}当前结果可以用于发现研究线索，不能直接证明治疗有效，也不能在缺少统一数据时生成候选排名。</div></section>`}
  function reviewControls(x){const v=s.review[x.pmid]||{};return `<details class="research-review"><summary>加入研究笔记 · ${v.reviewed?'已记录':'待记录'}</summary><label>研究类型（人工确认）<select data-research-review="${esc(x.pmid)}" data-review-field="evidenceType">${evidenceTypes.map(t=>`<option ${v.evidenceType===t?'selected':''}>${t}</option>`).join('')}</select></label><label>研究模型与条件<input data-research-review="${esc(x.pmid)}" data-review-field="model" maxlength="300" value="${esc(v.model||'')}" placeholder="从原文核对，不确定可留空"></label><label>支持的结论、局限与疑问<textarea data-research-review="${esc(x.pmid)}" data-review-field="note" maxlength="2000">${esc(v.note||'')}</textarea></label><label class="check-label"><input type="checkbox" data-research-review="${esc(x.pmid)}" data-review-field="reviewed" ${v.reviewed?'checked':''}>我已阅读并记录；不代表实验验证或疗效确证</label></details>`;}
  function quickQuestions(r){if(!r.researchId)return `<p class="research-expired">这是浏览器中保存的上次结果。重新检索后即可把文献带入 AI 助手。</p>`;const questions=['总结这些文献的主要发现，并逐条标注 PMID。','提取文献中可能涉及的天然产物或中药单体，并区分线索与已核验证据。','分析当前证据的研究类型、适用范围和主要局限。'];return `<section class="research-next"><div><span class="eyebrow">NEXT STEP</span><h2>让 AI 基于本轮文献继续分析</h2><p>将自动带入最多 3 篇相关题录和摘要片段，不会调用肺癌 EGFR 教学案例替代本轮资料。</p></div><div class="quick-question-grid">${questions.map((q,i)=>`<button data-research-prompt="${esc(q)}"><span>0${i+1}</span>${esc(q)}${icon('arrow-up-right')}</button>`).join('')}</div></section>`}
  function records(){const r=s.result;if(!r)return '';const all=r.records||[],filtered=s.filterType==='全部'?all:all.filter(x=>inferredType(x)===s.filterType);return `${overview(r)}${quickQuestions(r)}<section class="section research-results"><div class="section-head"><div><h2>文献记录</h2><p class="mini-note">先看研究类型和相关性，再展开摘要及笔记。</p></div><div class="result-tools"><label>证据类型<select id="evidenceFilter">${['全部',...evidenceTypes.filter(x=>x!=='未判定'&&x!=='其他'),'待判定'].map(x=>`<option ${s.filterType===x?'selected':''}>${x}</option>`).join('')}</select></label><span class="pill neutral">显示 ${filtered.length} / 本轮 ${all.length}</span><button id="researchExport">导出记录</button></div></div><details class="research-provenance"><summary>查看检索来源和实际查询式</summary><p>来源：${esc(r.source||'PubMed')}</p><p>获取时间：${esc(r.retrievedAt||'未提供')}</p><p>实际查询：${esc(r.query||'未提供')}${r.cached?' · 使用一小时内缓存':''}</p></details>${(r.warnings||[]).map(w=>`<p class="research-warning">${icon('triangle-alert')}${esc(w)}</p>`).join('')}<div class="research-record-list">${filtered.map((x,i)=>`<details class="research-record" ${i===0?'open':''}><summary><span class="record-index">${String(i+1).padStart(2,'0')}</span><span class="record-main"><strong>${esc(x.title||'无题名')}</strong><small>${esc(x.journal||'期刊未提供')} · ${esc(x.date||'日期未提供')}</small></span><span class="record-meta"><span class="evidence-type">${esc(inferredType(x))}</span><span>PMID ${esc(x.pmid||'')}</span></span></summary><div class="record-detail"><p class="abstract-excerpt">${esc(x.abstract||'当前记录未提供摘要，请打开 PubMed 查看原文。')}</p><div class="record-links">${safeUrl(x.url)?`<a href="${esc(safeUrl(x.url))}" target="_blank" rel="noopener noreferrer">查看 PubMed 原文 ${icon('external-link')}</a>`:''}${x.doi?`<span>DOI ${esc(x.doi)}</span>`:''}</div><button data-source-article="${esc(x.pmid)}">核对文献信息与全文入口</button>${reviewControls(x)}</div></details>`).join('')||'<p class="research-empty">当前筛选条件下没有文献记录，请切换其他证据类型。</p>'}</div></section>`}
  function moleculeText(x){if(x.error)return `<p class="research-error">${esc(x.error)}</p>`;if(x.loading)return '<p>正在查询分子身份…</p>';const r=x.result||x;if(r.error)return `<p class="research-error">PubChem：${esc(r.error)}</p>`;return `<p>${esc(r.name||'未提供名称')}${r.cid?' · CID '+esc(r.cid):''}${r.formula?' · 分子式 '+esc(r.formula):''}${r.molecularWeight?' · 分子量 '+esc(r.molecularWeight):''}</p>${r.inchiKey?`<p>InChIKey：${esc(r.inchiKey)}</p>`:''}${safeUrl(r.url)?`<a href="${esc(safeUrl(r.url))}" target="_blank" rel="noopener noreferrer">查看 PubChem</a>`:''}`}
  function naturalText(r){if(!r)return '';if(r.error)return `<p class="research-error">COCONUT：${esc(r.error)}</p>`;return `<div><strong>COCONUT 名称检索（需核对结构）</strong>${(r.records||[]).map(c=>`<p>${esc(c.name)} · ${esc(c.identifier)} ${safeUrl(c.url)?`<a href="${esc(safeUrl(c.url))}" target="_blank" rel="noopener noreferrer">查看记录</a>`:''}</p>`).join('')||'<p>未找到名称匹配记录。</p>'}</div>`;}
  function candidateView(){const a=s.result?.candidates||[];return `<section class="section candidate-section"><div class="section-head"><div><h2>可能相关的化学实体</h2><p class="mini-note">来自文献机器索引，只是下一步核对线索。</p></div><span class="pill warn">${a.length} 条 · 不排名</span></div>${a.length?`<div class="research-candidates">${a.map((c,i)=>`<article class="research-candidate"><div><strong>${esc(c.name||'未命名')}</strong><small>${esc(c.identifier||'无标识')}</small></div><span>${esc(c.status||'待核验')}</span><p>来源：${esc(c.source||'文献索引')} · ${(c.pmids||[]).map(p=>`<a href="https://pubmed.ncbi.nlm.nih.gov/${encodeURIComponent(p)}/" target="_blank" rel="noopener noreferrer">PMID ${esc(p)}</a>`).join('、')}</p><div class="research-candidate-actions"><button data-molecule="${esc(c.name||'')}" data-candidate="${i}">核对分子身份</button><button data-adopt-research="${i}" class="primary">选作讨论对象</button></div><div class="molecule-result">${s.lookup[i]?moleculeText(s.lookup[i])+naturalText(s.lookup[i].natural):''}</div></article>`).join('')}</div>`:'<div class="research-empty-state">本轮文献索引暂未提取出可核对的化学实体。你仍可让 AI 总结文献，但不要据此判断“没有相关中药单体”。</div>'}</section>`}
  function lookupView(){return `<details class="manual-lookup"><summary>手动核对一个化合物名称</summary><div><p>输入英文名称，分别查询 PubChem 身份和 COCONUT 天然产物记录。</p><label>成分英文名称<input id="moleculeQuery" maxlength="120" value="${esc(lookupQuery)}" placeholder="例如：liquiritin"></label><button id="researchLookup" ${lookupLoading?'disabled':''}>${lookupLoading?'查询中…':'查询分子与天然产物'}</button>${lookupData?lookupData.map((x,i)=>x.error?`<p class="research-error">${i===0?'PubChem':'COCONUT'}：${esc(x.error)}</p>`:i===0?`<div class="molecule-result">${moleculeText(x)}</div>`:`<div>${naturalText(x)}</div>`).join(''):''}</div></details>`}
  function sourceDetails(){return `<details class="source-details"><summary>数据库覆盖范围与当前限制</summary><div class="source-grid"><div><strong>PubMed / Europe PMC</strong><span>在线检索，展示实际来源</span></div><div><strong>TCMSP</strong><span>外部人工核对，待授权导入</span></div><div><strong>HERB</strong><span>外部人工核对，待授权导入</span></div></div></details>`}
  function taskPanel(){return s.loading?loadingView():searchForm()}
  function evidence(){if(!s.result)return `<section class="research-empty-page"><div>${icon('search')}<h2>还没有本轮检索结果</h2><p>先输入一个疾病名称，系统才会建立对应的文献研究记录。</p><button data-next="task" class="primary">返回开始研究</button></div></section>`;return `<div id="researchEvidenceMount">${progress()}${records()}${candidateView()}${lookupView()}${window.SourceUI?.panel()||''}${sourceDetails()}</div>`}

  function stopLoadingTimer(){if(loadingTimer){clearInterval(loadingTimer);loadingTimer=null}}
  async function search(){const d=(document.querySelector('#researchDisease')?.value||s.disease||'').trim();if(!d){s.error='请先填写疾病名称。';save();window.render?.();return}s={...s,disease:d,target:(document.querySelector('#researchTarget')?.value||s.target||'').trim(),compound:(document.querySelector('#researchCompound')?.value||s.compound||'').trim(),loading:true,loadingStage:0,elapsed:0,error:'',result:null,lookup:{},filterType:'全部'};save();window.render?.();activeController=new AbortController();loadingTimer=setInterval(()=>{s.elapsed+=1;s.loadingStage=s.elapsed<2?0:s.elapsed<6?1:s.elapsed<10?2:3;window.render?.()},1000);const timeout=setTimeout(()=>activeController?.abort('timeout'),90000);try{const res=await fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({disease:s.disease,target:s.target,compound:s.compound,limit:8}),signal:activeController.signal});const data=await res.json().catch(()=>({}));if(!res.ok||!Array.isArray(data.records))throw new Error(data.error||`检索失败（${res.status}）`);s.result=data;rememberResearch(data);s.loading=false;s.loadingStage=0;save();location.hash='evidence';window.render?.()}catch(e){s.loading=false;s.loadingStage=0;s.error=e.name==='AbortError'?(activeController?.signal.reason==='user'?'本次检索已取消。':'检索超时，请重试。'):(e.message||'暂时无法连接检索服务。');save();window.render?.()}finally{clearTimeout(timeout);stopLoadingTimer();activeController=null}}
  function cancelSearch(){if(activeController)activeController.abort('user')}
  async function molecule(name,i){s.lookup[i]={loading:true};save();window.render?.();const results=await Promise.all(['/api/compound','/api/natural-product'].map(async url=>{const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),60000);try{const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name}),signal:ctl.signal});const d=await res.json();if(!res.ok)throw new Error(d.error||'查询失败');return d}catch(e){return {error:e.message}}finally{clearTimeout(timer)}}));s.lookup[i]={result:results[0],natural:results[1]};save();window.render?.()}
  function exportData(){if(!s.result)return;const r=s.result,p={researchId:r.researchId||'',disease:r.disease,query:r.query,total:r.total,retrievedAt:r.retrievedAt,source:r.source||'PubMed',candidates:r.candidates||[],review:s.review,identityQueries:s.lookup,warnings:r.warnings||[],records:(r.records||[]).map(x=>({pmid:x.pmid,title:x.title,journal:x.journal,date:x.date,doi:x.doi,url:x.url,abstract:(x.abstract||'').slice(0,250)})),exportedAt:new Date().toISOString()},a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(p,null,2)],{type:'application/json'}));a.download='research-'+(r.researchId||'pubmed')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  async function lookupMolecule(){if(lookupLoading)return;lookupQuery=(document.querySelector('#moleculeQuery')?.value||'').trim();if(!lookupQuery)return;lookupLoading=true;lookupData=null;window.render?.();lookupData=await Promise.all(['/api/compound','/api/natural-product'].map(async url=>{const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),60000);try{const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:lookupQuery}),signal:ctl.signal});const data=await res.json();if(!res.ok)throw new Error(data.error||'查询失败');return data}catch(e){return {error:e.message||'查询失败'}}finally{clearTimeout(timer)}}));lookupLoading=false;window.render?.()}
  function askResearch(question){if(window.HerbChat?.ask){window.HerbChat.ask(question);setTimeout(()=>document.querySelector('#assistant')?.scrollIntoView({behavior:'smooth',block:'start'}),50)}}
  window.ResearchUI={taskPanel,evidencePanel:evidence,candidatePanel:candidateView,hasResult:()=>!!s.result,scope:()=>s.result?.researchId?`已带入 ${s.result.records.length} 篇本轮文献；向智能体提问时最多附带 3 篇相关题录与摘要片段。`:'尚未附带本轮文献。请先开始研究或重新检索。',getResearchId:()=>s.result?.researchId||'',provenance:()=>s.result?`实时检索来源：${s.result.source||'PubMed'}；researchId：${s.result.researchId||'未提供'}；查询：${s.result.query||'未提供'}；获取时间：${s.result.retrievedAt||'未提供'}；记录数：${s.result.total??s.result.records?.length??0}`:'未进行实时检索。'};
  document.addEventListener('click',e=>{const example=e.target.closest('[data-example-disease]');if(example){s.disease=example.dataset.exampleDisease;s.error='';save();window.render?.();setTimeout(()=>document.querySelector('#researchDisease')?.focus(),0)}const open=e.target.closest('[data-history-open]');if(open)openHistory(open.dataset.historyOpen);const rename=e.target.closest('[data-history-rename]');if(rename)renameHistory(rename.dataset.historyRename);const quick=e.target.closest('[data-research-prompt]');if(quick)askResearch(quick.dataset.researchPrompt);if(e.target.closest('#researchCancel'))cancelSearch();if(e.target.closest('#researchLookup'))lookupMolecule();if(e.target.closest('#researchSearch'))search();if(e.target.closest('#researchExport'))exportData();const chosen=e.target.closest('[data-adopt-research]');if(chosen){const c=s.result?.candidates?.[Number(chosen.dataset.adoptResearch)];if(c&&window.HerbWorkspace){HerbWorkspace.selectResearchCandidate(c,{disease:s.result.disease,target:s.target,query:s.result.query,retrievedAt:s.result.retrievedAt,source:s.result.source,records:s.result.records.filter(r=>c.pmids.includes(r.pmid)),review:Object.fromEntries(c.pmids.filter(p=>s.review[p]).map(p=>[p,s.review[p]]))});location.hash='experiment'}}const b=e.target.closest('[data-molecule]');if(b)molecule(b.dataset.molecule,b.dataset.candidate)});
  function saveReview(e){const p=e.target.dataset.researchReview,f=e.target.dataset.reviewField;if(!p||!f)return;const v=s.review[p]||{};v[f]=f==='reviewed'?e.target.checked:e.target.value;v.updatedAt=new Date().toISOString();s.review[p]=v;save();if(f==='reviewed')window.render?.()}
  document.addEventListener('change',e=>{saveReview(e);if(e.target.id==='evidenceFilter'){s.filterType=e.target.value;save();window.render?.()}});
  document.addEventListener('input',e=>{if(e.target.dataset.researchReview&&e.target.dataset.reviewField!=='reviewed')saveReview(e);const m={researchDisease:'disease',researchTarget:'target',researchCompound:'compound'};if(m[e.target.id]){s[m[e.target.id]]=e.target.value;save()}});
})();
