(function(){
  const KEY='herblab-research-v1';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const safeUrl=v=>{try{const u=new URL(String(v));return /^https?:$/.test(u.protocol)?u.href:''}catch{return ''}};
  const initial={disease:'',target:'',compound:'',result:null,loading:false,error:'',lookup:{},review:{}};let s={...initial};
  try{const x=JSON.parse(localStorage.getItem(KEY));if(x&&typeof x==='object')s={...s,...x}}catch{}
  s.loading=false; s.review=s.review&&typeof s.review==='object'?s.review:{}; s.lookup=Object.fromEntries(Object.entries(s.lookup||{}).filter(([,v])=>v&&!v.loading)); if(s.result)s.result={...s.result,researchId:''};
  function save(){try{localStorage.setItem(KEY,JSON.stringify(s))}catch{}}
  function form(){return `<section class="section flow-card research-panel"><div class="section-head"><h2>实时文献检索</h2><span class="research-status">${s.loading?'正在检索…':s.result?'已获取文献结果':'等待明确检索'}</span></div><p class="research-lead">输入疾病后点击“开始检索”，服务端会按疾病别名检索 PubMed；直连接口不可用时使用 Europe PMC 的 PubMed 记录。不会根据需求文字自动检索。</p><div class="research-form"><label>疾病或常用别名<input id="researchDisease" maxlength="120" value="${esc(s.disease)}" placeholder="例如：三叉神经痛 / trigeminal neuralgia"></label><label>可选靶点<input id="researchTarget" maxlength="120" value="${esc(s.target)}" placeholder="例如：SCN9A"></label><label>可选化合物（英文）<input id="researchCompound" maxlength="120" value="${esc(s.compound)}" placeholder="例如：Quercetin"></label></div><div class="research-actions"><button id="researchSearch" class="primary" ${s.loading?'disabled':''}>${s.loading?'检索中…':'开始检索'}</button><button id="researchExample">填入示例</button>${s.result?'<button id="researchExport">导出本次检索</button>':''}</div>${s.error?`<p class="research-error" role="alert">${esc(s.error)}</p>`:''}<div class="source-grid"><div><strong>PubMed / Europe PMC</strong><span>在线检索 · 显示实际来源</span></div><div><strong>TCMSP</strong><span>外部手工核对，待授权导入</span></div><div><strong>HERB</strong><span>外部手工核对，待授权导入</span></div></div></section>`}
  const evidenceTypes=['未判定','细胞实验','动物实验','临床研究','计算预测','综述','其他'];
  function reviewControls(x){const v=s.review[x.pmid]||{};return `<details class="research-review"><summary>人工核对与证据笔记 · ${v.reviewed?'已记录阅读确认':'待核对'}</summary><label>研究类型（人工判断）<select data-research-review="${esc(x.pmid)}" data-review-field="evidenceType">${evidenceTypes.map(t=>`<option ${v.evidenceType===t?'selected':''}>${t}</option>`).join('')}</select></label><label>研究模型与条件<input data-research-review="${esc(x.pmid)}" data-review-field="model" maxlength="300" value="${esc(v.model||'')}" placeholder="从原文核对，不确定可留空"></label><label>支持的结论、局限与疑问<textarea data-research-review="${esc(x.pmid)}" data-review-field="note" maxlength="2000">${esc(v.note||'')}</textarea></label><label class="check-label"><input type="checkbox" data-research-review="${esc(x.pmid)}" data-review-field="reviewed" ${v.reviewed?'checked':''}>我已阅读并记录；此确认不代表实验验证或疗效确证</label></details>`;}
  function progress(){const r=s.result;const read=(r?.records||[]).filter(x=>s.review[x.pmid]?.reviewed).length;const c=window.HerbWorkspace?.currentCandidate?.();return `<section class="section research-progress"><div class="section-head"><h2>本轮研究进度</h2><span class="pill neutral">${r?'有检索记录':'等待检索'}</span></div><div class="research-step-grid"><div><strong>1 · 需求</strong><span>${esc(r?.disease?.label||s.disease||'未填写')}</span></div><div><strong>2 · 文献</strong><span>${r?.records?.length||0} 篇题录 · ${read} 篇人工阅读确认</span></div><div><strong>3 · 化学线索</strong><span>${r?.candidates?.length||0} 条 · 身份与相关性待核对</span></div><div><strong>4 · 讨论对象</strong><span>${esc(c?.name||'尚未选择')} · ${c?.origin==='research'?'外部检索线索':'EGFR教学案例'}</span></div></div><p class="mini-note">本卡记录网页操作进度。人工阅读确认、名称命中和选择讨论对象都不是实验验证；完整 Agent 调度尚未实现。</p></section>`;}
  function records(){const r=s.result;if(!r)return '';return `<section class="section research-results"><div class="section-head"><div><h2>本次检索结果</h2><p class="mini-note">范围：${esc(r.disease?.label||'')}（实际检索式见下方）</p></div><span class="pill neutral">${esc(r.total??r.records?.length??0)} 条</span></div><div class="research-provenance">来源：${esc(r.source||'PubMed')} · 获取时间：${esc(r.retrievedAt||'未提供')} · 查询：${esc(r.query||'未提供')} ${r.cached?' · 使用一小时内的缓存':''}</div>${!r.researchId?'<p class="mini-note">这是上次保存的结果；重新检索后才能用于本轮 AI 问答。</p>':''}<div class="research-actions"><button id="researchAsk" ${r.researchId?'':'disabled'}>用这些文献提问</button><button data-next="ranking">查看候选线索</button></div>${(r.warnings||[]).map(w=>`<p class="mini-note">${esc(w)}</p>`).join('')}${(r.records||[]).map(x=>`<article class="research-record"><div class="research-record-head"><strong>${esc(x.title||'无题名')}</strong><span>PMID ${esc(x.pmid||'')}</span></div><p>${esc(x.journal||'期刊未提供')} · ${esc(x.date||'日期未提供')}${x.doi?' · DOI '+esc(x.doi):''}</p><p class="abstract-excerpt">${esc((x.abstract||'未提供摘要').slice(0,250))}${(x.abstract||'').length>250?'…':''}</p>${safeUrl(x.url)?`<a href="${esc(safeUrl(x.url))}" target="_blank" rel="noopener noreferrer">查看 PubMed 原文</a>`:''}${reviewControls(x)}</article>`).join('')||'<p class="research-empty">服务端未返回文献记录，请调整疾病或稍后重试。</p>'}</section>`}
  function moleculeText(x){if(x.error)return `<p class="research-error">${esc(x.error)}</p>`;if(x.loading)return '<p>正在查询分子身份…</p>'; const r=x.result||x; if(r.error)return `<p class="research-error">PubChem：${esc(r.error)}</p>`;return `<p>${esc(r.name||'未提供名称')}${r.cid?' · CID '+esc(r.cid):''}${r.formula?' · 分子式 '+esc(r.formula):''}${r.molecularWeight?' · 分子量 '+esc(r.molecularWeight):''}</p>${r.inchiKey?`<p>InChIKey：${esc(r.inchiKey)}</p>`:''}${safeUrl(r.url)?`<a href="${esc(safeUrl(r.url))}" target="_blank" rel="noopener noreferrer">查看 PubChem</a>`:''}`}
  function naturalText(r){if(!r)return '';if(r.error)return `<p class="research-error">COCONUT：${esc(r.error)}</p>`;return `<div><strong>COCONUT 名称检索（需核对结构）</strong>${(r.records||[]).map(c=>`<p>${esc(c.name)} · ${esc(c.identifier)} ${safeUrl(c.url)?`<a href="${esc(safeUrl(c.url))}" target="_blank" rel="noopener noreferrer">查看记录</a>`:''}</p><p class="mini-note">SMILES：${esc(c.smiles)}</p>`).join('')||'<p>未找到名称匹配记录。</p>'}</div>`;}
  function candidateView(){const a=s.result?.candidates||[];if(!a.length)return '';return `<section class="section"><div class="section-head"><h2>候选化合物线索</h2><span class="pill warn">仅供核对 · 不排名</span></div><p class="mini-note">候选来自服务端线索，不是已验证的中药单体，也不会套用 EGFR 教学排序。</p><div class="research-candidates">${a.map((c,i)=>`<article class="research-candidate"><div><strong>${esc(c.name||'未命名')}</strong><small>${esc(c.identifier||'无标识')}</small></div><span>${esc(c.status||'待核验')}</span><div class="research-candidate-actions"><button data-molecule="${esc(c.name||'')}" data-candidate="${i}">查询分子身份</button><button data-adopt-research="${i}" class="primary">选作讨论对象</button></div><p class="mini-note">来源：${esc(c.source||'PubTator3')} · 文献：${(c.pmids||[]).map(p=>`<a href="https://pubmed.ncbi.nlm.nih.gov/${encodeURIComponent(p)}/" target="_blank" rel="noopener noreferrer">PMID ${esc(p)}</a>`).join('、')}</p><div class="molecule-result">${s.lookup[i]?moleculeText(s.lookup[i])+naturalText(s.lookup[i].natural):''}</div></article>`).join('')}</div></section>`}
  function view(){return progress()+form()+records()+candidateView()+lookupView()}
  function evidence(){return `<div id="researchEvidenceMount">${view()}<section class="section"><div class="section-head"><h2>外部数据库状态</h2></div><p class="mini-note">TCMSP 与 HERB 当前仅展示人工核对入口，导入前需要授权和来源审查。</p><div class="evidence-links"><a href="https://old.tcmsp-e.com/tcmsp.php" target="_blank" rel="noopener noreferrer">TCMSP 官网</a><a href="http://herb.ac.cn/v2/" target="_blank" rel="noopener noreferrer">HERB 官网</a></div></section></div>`}
  async function search(){const d=(document.querySelector('#researchDisease')?.value||'').trim();if(!d){s.error='请先填写疾病或常用别名。';save();window.render?.();return}s={...s,disease:d,target:(document.querySelector('#researchTarget')?.value||'').trim(),compound:(document.querySelector('#researchCompound')?.value||'').trim(),loading:true,error:'',result:null,lookup:{}};save();window.render?.();try{const c=new AbortController(),t=setTimeout(()=>c.abort(),90000),res=await fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({disease:s.disease,target:s.target,compound:s.compound,limit:8}),signal:c.signal});clearTimeout(t);const data=await res.json().catch(()=>({}));if(!res.ok||!Array.isArray(data.records))throw new Error(data.error||`检索失败（${res.status}）`);s.result=data;s.loading=false;save();location.hash='evidence';window.render?.()}catch(e){s.loading=false;s.error=e.name==='AbortError'?'检索超时，请重试。':(e.message||'暂时无法连接检索服务。');save();window.render?.()}}
  async function molecule(name,i){s.lookup[i]={loading:true};save();window.render?.();const results=await Promise.all(['/api/compound','/api/natural-product'].map(async url=>{const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),60000);try{const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name}),signal:ctl.signal});const d=await res.json();if(!res.ok)throw new Error(d.error||'查询失败');return d}catch(e){return {error:e.message}}finally{clearTimeout(timer)}}));s.lookup[i]={result:results[0],natural:results[1]};save();window.render?.()}
  function exportData(){if(!s.result)return;const r=s.result,p={researchId:r.researchId||'',disease:r.disease,query:r.query,total:r.total,retrievedAt:r.retrievedAt,source:r.source||'PubMed',candidates:r.candidates||[],review:s.review,identityQueries:s.lookup,warnings:r.warnings||[],records:(r.records||[]).map(x=>({pmid:x.pmid,title:x.title,journal:x.journal,date:x.date,doi:x.doi,url:x.url,abstract:(x.abstract||'').slice(0,250)})),exportedAt:new Date().toISOString()},a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(p,null,2)],{type:'application/json'}));a.download='research-'+(r.researchId||'pubmed')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

  let lookupQuery='', lookupData=null, lookupLoading=false;
  function lookupView(){return `<section class="section"><div class="section-head"><h2>核对分子身份与天然产物记录</h2><span class="pill neutral">PubChem · COCONUT</span></div><p class="mini-note">输入英文成分名称，查询分子身份和天然产物记录。PubChem 受上游访问限制时会显示失败，COCONUT 仍可单独查询；名称相近的衍生物可能是不同分子。</p><label>成分英文名称<input id="moleculeQuery" maxlength="120" value="${esc(lookupQuery)}" placeholder="例如：liquiritin"></label><button id="researchLookup" ${lookupLoading?'disabled':''}>${lookupLoading?'查询中…':'查询分子与天然产物'}</button>${lookupData?lookupData.map((x,i)=>x.error?`<p class="research-error">${i===0?'PubChem':'COCONUT'}：${esc(x.error)}</p>`:i===0?`<div class="molecule-result">${moleculeText(x)}</div>`:`<div><h3>COCONUT 名称检索结果</h3>${(x.records||[]).map(c=>`<p><strong>${esc(c.name)}</strong> · ${esc(c.identifier)} ${safeUrl(c.url)?`<a href="${esc(safeUrl(c.url))}" target="_blank" rel="noopener noreferrer">查看记录</a>`:''}</p><p class="mini-note">SMILES：${esc(c.smiles)}</p>`).join('')||'<p>未找到名称匹配记录。</p>'}</div>`).join(''):''}</section>`}
  async function lookupMolecule(){if(lookupLoading)return;lookupQuery=(document.querySelector('#moleculeQuery')?.value||'').trim();if(!lookupQuery)return;lookupLoading=true;lookupData=null;window.render?.();lookupData=await Promise.all(['/api/compound','/api/natural-product'].map(async url=>{const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),60000);try{const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:lookupQuery}),signal:ctl.signal});const data=await res.json();if(!res.ok)throw new Error(data.error||'查询失败');return data}catch(e){return {error:e.message||'查询失败'}}finally{clearTimeout(timer)}}));lookupLoading=false;window.render?.();}
  window.ResearchUI={taskPanel:()=>progress()+form()+lookupView(),evidencePanel:evidence,candidatePanel:candidateView,hasResult:()=>!!s.result,scope:()=>s.result?.researchId?`本轮文献：${s.result.disease?.label||s.disease} · ${s.result.records.length} 篇。提问会带入最多三篇相关题录与摘要片段；请核对原文。`:'可点击开始检索，获取新疾病文献后再向智能体提问。',getResearchId:()=>s.result?.researchId||'',provenance:()=>s.result?`实时检索来源：${s.result.source||'PubMed'}；researchId：${s.result.researchId||'未提供'}；查询：${s.result.query||'未提供'}；获取时间：${s.result.retrievedAt||'未提供'}；记录数：${s.result.total??s.result.records?.length??0}`:'未进行实时检索。'};
  document.addEventListener('click',e=>{if(e.target.closest('#researchAsk')){const draft=document.querySelector('#chatDraft');if(draft){draft.value='请根据本次检索文献，整理候选化学物质、研究模型和证据局限，逐条给出 PMID。区分文献线索与经过核验的中药单体，不生成没有数据的排名。';draft.dispatchEvent(new Event('input',{bubbles:true}));draft.focus()}}if(e.target.closest('#researchLookup'))lookupMolecule();if(e.target.closest('#researchSearch'))search();if(e.target.closest('#researchExample')){s.disease='三叉神经痛';s.target='';s.compound='';save();window.render?.()}if(e.target.closest('#researchExport'))exportData();const chosen=e.target.closest('[data-adopt-research]');if(chosen){const c=s.result?.candidates?.[Number(chosen.dataset.adoptResearch)];if(c&&window.HerbWorkspace){HerbWorkspace.selectResearchCandidate(c,{disease:s.result.disease,target:s.target,query:s.result.query,retrievedAt:s.result.retrievedAt,source:s.result.source,records:s.result.records.filter(r=>c.pmids.includes(r.pmid)),review:Object.fromEntries(c.pmids.filter(p=>s.review[p]).map(p=>[p,s.review[p]]))});}}const b=e.target.closest('[data-molecule]');if(b)molecule(b.dataset.molecule,b.dataset.candidate)});
  function saveReview(e){const p=e.target.dataset.researchReview,f=e.target.dataset.reviewField;if(!p||!f)return;const v=s.review[p]||{};v[f]=f==='reviewed'?e.target.checked:e.target.value;v.updatedAt=new Date().toISOString();s.review[p]=v;save();if(f==='reviewed')window.render?.();}
  document.addEventListener('change',saveReview);
  document.addEventListener('input',e=>{if(e.target.dataset.researchReview&&e.target.dataset.reviewField!=='reviewed')saveReview(e);const m={researchDisease:'disease',researchTarget:'target',researchCompound:'compound'};if(m[e.target.id]){s[m[e.target.id]]=e.target.value;save()}});
})();
