(function(){
  'use strict';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const types={target:{title:'UniProt 人类靶点',hint:'基因名，例如 EGFR、SCN9A',field:'query',api:'/api/target'},molecule:{title:'ChEMBL 化合物身份',hint:'英文名，例如 Quercetin',field:'name',api:'/api/chembl-molecule'},bioactivity:{title:'ChEMBL 实验活性',hint:'确认身份后的 CHEMBL 编号',field:'moleculeId',api:'/api/bioactivity'},article:{title:'文献核对与开放全文',hint:'PMID，例如 24471765',field:'pmid',api:'/api/article'}};
  const state=Object.fromEntries(Object.keys(types).map(k=>[k,{query:'',loading:false,result:null,error:''}]));
  const link=url=>{try{const u=new URL(url);return u.protocol==='https:'?`<a href="${esc(u.href)}" target="_blank" rel="noopener noreferrer">查看来源记录</a>`:''}catch{return ''}};
  const labels={accession:'UniProt 编号',gene:'基因',genes:'基因',proteinName:'蛋白名称',organism:'物种',reviewed:'人工审阅',identifier:'记录编号',moleculeId:'化合物编号',molecule_chembl_id:'化合物编号',chemblId:'ChEMBL 编号',name:'名称',prefName:'首选名称',smiles:'SMILES',inchiKey:'InChIKey',targetId:'靶点编号',targetName:'靶点',assayId:'实验编号',assayType:'实验类型',type:'测量类型',relation:'关系',value:'数值',units:'单位',standardType:'标准测量类型',standardRelation:'关系',standardValue:'标准数值',standardUnits:'标准单位',validityComment:'有效性备注',dataValidityComment:'有效性备注',potentialDuplicate:'可能重复',documentId:'文献编号',pmid:'PMID',pmcid:'PMCID',title:'题名',journal:'期刊',doi:'DOI',date:'日期',abstract:'摘要',isOpenAccess:'开放获取',openAccess:'开放获取'};
  function recordView(x){
    const flat={...x,proteinName:x.proteinName||x.protein,assayId:x.assay?.id,assayType:x.assay?.type,targetId:x.target?.id,targetName:x.target?.name,organism:x.organism||x.target?.organism,documentId:x.document?.id,dataValidityComment:x.validity,potentialDuplicate:x.flags?.potentialDuplicate};
    const links=[x.url,x.fullTextUrl,x.document?.url,x.links?.pubmed,x.links?.europePmc,x.links?.pmc].filter(Boolean);
    return `<article class="research-candidate"><dl>${Object.entries(flat).filter(([f,v])=>labels[f]&&v!==undefined&&v!==null&&v!==''&&typeof v!=='object').map(([f,v])=>`<dt>${labels[f]}</dt><dd>${esc(typeof v==='boolean'?(v?'是':'否'):v)}</dd>`).join('')}</dl>${x.assay?.description?`<p>实验条件：${esc(x.assay.description)}</p>`:''}${links.map(link).join(' · ')}${(x.links?.fullText||[]).map(z=>`<p>${link(z.url)} · ${esc(z.availability||'访问条件待核验')}</p>`).join('')}${x.moleculeId||x.chemblId||x.molecule_chembl_id?`<button data-source-activity="${esc(x.moleculeId||x.chemblId||x.molecule_chembl_id)}">我已核对身份，查询活性</button>`:''}</article>`;
  }
  function resultView(k){const a=state[k],r=a.result;if(a.error)return `<p class="research-error" role="alert">${esc(a.error)}</p>`;if(!r)return '';return `<div><p>来源：${esc(r.source)} · 获取时间：${esc(r.retrievedAt)} · 展示 ${(r.records||[]).length} / 命中 ${esc(r.total??(r.records||[]).length)}</p>${(r.warnings||[]).map(w=>`<p class="research-warning">${esc(w)}</p>`).join('')}${(r.records||[]).map(recordView).join('')||'<p>未找到匹配记录；这不代表不存在相关研究。</p>'}<button data-source-export="${k}">导出来源与查询结果</button></div>`}
  function panel(){return `<details class="source-details" ${Object.values(state).some(a=>a.loading||a.result||a.error)?'open':' '}><summary>查询原规划数据库与文献库</summary><p>靶点身份、化合物身份和实验活性分别核对。不同实验条件与单位不能直接用于双排序；全文仅提供开放获取入口。</p>${Object.entries(types).map(([k,t])=>`<section class="manual-lookup"><h3>${t.title}</h3><label>${t.hint}<input data-source-input="${k}" maxlength="120" value="${esc(state[k].query)}"></label><button data-source-query="${k}" ${state[k].loading?'disabled':''}>${state[k].loading?'查询中…':'查询'}</button>${resultView(k)}</section>`).join('')}</details>`}
  async function query(k){const t=types[k],a=state[k];if(a.loading)return;if(!a.query.trim()){a.error='请先输入查询内容。';window.render?.();return}a.loading=true;a.result=null;a.error='';window.render?.();try{const r=await fetch(t.api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({[t.field]:a.query.trim()}),signal:AbortSignal.timeout(30000)});const d=await r.json();if(!r.ok)throw new Error(d.error||'数据库查询失败。');a.result=d}catch(e){a.error=e.name==='TimeoutError'?'查询超时，请稍后重试。':e.message}finally{a.loading=false;window.render?.()}}
  document.addEventListener('input',e=>{const k=e.target.dataset.sourceInput;if(types[k])state[k].query=e.target.value});
  document.addEventListener('click',e=>{const b=e.target.closest('[data-source-article]');if(b){state.article.query=b.dataset.sourceArticle;query('article').then(()=>{const input=document.querySelector('[data-source-input="article"]');if(input){input.closest('details').open=true;input.scrollIntoView({behavior:'smooth',block:'center'})}})}});
  document.addEventListener('click',e=>{const b=e.target.closest('[data-source-query]');if(b)query(b.dataset.sourceQuery);const activity=e.target.closest('[data-source-activity]');if(activity){state.bioactivity.query=activity.dataset.sourceActivity;query('bioactivity')}const ex=e.target.closest('[data-source-export]');if(ex){const k=ex.dataset.sourceExport;if(!state[k]?.result)return;const url=URL.createObjectURL(new Blob([JSON.stringify({query:state[k].query,...state[k].result},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${k}-query.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}});
  window.SourceUI={panel};
})();
