(function(){
 'use strict';
 const key='herblab-structure-pool-v1',esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let s={names:'',reference:'',accession:'',query:'',pool:[],result:null,error:'',loading:false};
 try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&typeof saved==='object')s={...s,...saved,loading:false}}catch{}
 const statusLabel=x=>({computed:'已计算',pending:'待补',unavailable:'未指定靶点',recorded:'有实验记录',no_record:'未查到记录'}[x]||x||'待补');
 const save=()=>{try{localStorage.setItem(key,JSON.stringify({...s,loading:false}))}catch{}};
 const repaint=()=>window.render?.();
 const link=u=>{try{const x=new URL(u);return x.protocol==='https:'?`<a href="${esc(x.href)}" target="_blank" rel="noopener noreferrer">来源</a>`:''}catch{return ''}};
 function parsePool(data){
  const rows=Array.isArray(data)?data:data?.records;
  if(!Array.isArray(rows)||!rows.length||rows.length>1000)throw new Error('请提供 1–1000 条成分 records；不需要文献记录。');
  const found=new Set();return rows.map((r,i)=>{
   if(!r||typeof r.name!=='string'||!r.name.trim()||r.name.length>100)throw new Error(`第 ${i+1} 条缺少有效成分名称。`);
   const id=String(r.candidateId||r.identifier||r.cid||r.name);if(found.has(id))throw new Error('候选编号重复，请先去重。');found.add(id);
   const keep=(value,max=500)=>typeof value==='string'?value.slice(0,max):Number.isFinite(value)?value:null;
   return {id,name:r.name.trim(),cid:r.cid??null,smiles:typeof r.smiles==='string'?r.smiles.slice(0,3000):'',sourceHerb:typeof r.sourceHerb==='string'?r.sourceHerb:'',source:typeof r.source==='string'?r.source:typeof data?.provenance?.source==='string'?data.provenance.source:'用户导入·待核验',url:typeof r.url==='string'?r.url:typeof data?.provenance?.rawUrl==='string'?data.provenance.rawUrl:'',target:keep(r.target),channel:keep(r.channel),affinity:keep(r.affinity),admet:keep(r.admet),bbb:keep(r.bbb),toxicity:keep(r.toxicity),dimensionSource:typeof r.dimensionSource==='string'?r.dimensionSource.slice(0,1000):''};
  });
 }
 function download(name,data){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
 function template(){const result=s.result;if(!result?.candidates?.length)throw new Error('请先计算结构相似度。');const target=s.accession||'待确认靶点';return {metadata:{version:`structure-pool-${Date.now()}`,target,matchPolicy:'structure-target-affinity-review-v1',matchWeights:[1,1,1],filterPolicy:'teacher-structure-risk-v1',description:'结构子分为 PubChem 指纹相似度；靶点与亲和力子分需同协议计算及人工核验，不以文献数量补分。'},candidates:result.candidates.map((c,i)=>({id:`S${i+1}`,name:c.name,identity:{status:'pending',source:c.identity?.sourceURL||c.identity?.url||''},filter:{status:'unknown',source:'',policy:'teacher-structure-risk-v1'},match:{score:null,source:'',target,policy:'structure-target-affinity-review-v1',components:{structure:{value:c.structure?.status==='computed'?c.structure.score:null,source:c.structure?.status==='computed'?JSON.stringify({method:c.structure.method,referenceCID:c.structure.referenceCID,queriedAt:result.queriedAt||result.provenance?.queriedAt,source:c.identity?.sourceURL||c.identity?.url}):''},channel:{value:null,source:''},affinity:{value:null,source:''}}},evidence:'未要求疾病相关文献；数据库活性记录见原始计算导出',risk:'结构过滤、靶点关联和亲和力评分待核验'}))};}
 function results(){if(!s.result)return '';const rows=s.result.candidates||[],ranked=rows.filter(x=>x.structure?.status==='computed'&&Number.isFinite(x.structure.score)).sort((a,b)=>b.structure.score-a.structure.score);return `<section class="section"><h3>结构相似度排序 · 参考 CID ${esc(s.result.reference?.cid||'待核对')}</h3><p>这一排名仅比较参考分子的二维结构。它不证明同靶点、同作用方向或同适应症；缺少亲和力、ADMET、BBB 与毒性的数据保留待补。</p><div class="table-scroll"><table><thead><tr><th>名次</th><th>成分</th><th>结构相似度分</th><th>靶点结合记录</th></tr></thead><tbody>${ranked.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.name)}</td><td>${x.structure.score.toFixed(2)}</td><td>${esc(statusLabel(x.binding?.status))} · ${esc(x.binding?.total??'未知')}</td></tr>`).join('')}</tbody></table></div>${rows.map(x=>`<details><summary>${esc(x.name)} · ${esc(statusLabel(x.structure?.status))}</summary><p>${link(x.identity?.sourceURL||x.identity?.url)} ${esc(x.identity?.inchiKey||'身份待核对')}</p><pre class="rank-source">${esc(JSON.stringify({structure:x.structure,binding:x.binding,error:x.error},null,2))}</pre></details>`).join('')}<div class="button-row"><button id="structureExport">导出结构与活性原始记录</button><button id="structureRankTemplate">导出完整匹配待补模板</button></div></section>`;}
 function dimensionValue(v){return v===null||v===undefined||v===''?'<span class="pill warn">待接入</span>':`<span class="pill neutral">${esc(v)}</span>`}
 function dimensionTable(){if(!s.result?.candidates?.length)return '';const rows=s.result.candidates.map(candidate=>{const imported=s.pool.find(x=>String(x.cid||x.name).toLowerCase()===String(candidate.identity?.cid||candidate.name).toLowerCase())||s.pool.find(x=>String(x.name).toLowerCase()===String(candidate.name).toLowerCase())||{};const structure=candidate.structure?.status==='computed'?candidate.structure.score.toFixed(2):null;const binding=candidate.binding?.status==='recorded'?`${candidate.binding.total} 条 ChEMBL 记录`:null;const completed=[structure,imported.target||imported.channel,binding||imported.affinity,imported.admet,imported.bbb,imported.toxicity].filter(x=>x!==null&&x!==undefined&&x!=='').length;return {candidate,imported,structure,binding,completed}});return `<section class="section dimension-matrix"><div class="section-head"><div><h3>模式二 · 多维数据完整性</h3><p class="mini-note">结构、靶点／通道、亲和力、ADMET、BBB、毒性分别保留；没有真实数据时显示“待接入”，不会补零。</p></div></div><div class="table-scroll"><table><thead><tr><th>候选</th><th>结构</th><th>靶点／通道</th><th>亲和力／活性</th><th>ADMET</th><th>BBB</th><th>毒性</th><th>可排序性</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.candidate.name)}</td><td>${dimensionValue(x.structure)}</td><td>${dimensionValue(x.imported.target||x.imported.channel)}</td><td>${dimensionValue(x.binding||x.imported.affinity)}</td><td>${dimensionValue(x.imported.admet)}</td><td>${dimensionValue(x.imported.bbb)}</td><td>${dimensionValue(x.imported.toxicity)}</td><td>${x.completed===6?'<span class="pill success">字段齐全·仍需统一量纲</span>':`<span class="pill warn">${x.completed}/6 维有数据</span>`}</td></tr>`).join('')}</tbody></table></div><p class="boundary-note">“字段齐全”仅代表可进入统一规则评估；在团队确定量纲、方向和权重前，不生成综合疗效排名。</p></section>`}
 const baseResults=results;results=function(){return baseResults()+dimensionTable()};
 function panel(){return `<section class="section structure-panel"><span class="eyebrow">STRUCTURE FIRST / 独立成分候选池</span><h2>从成分出发，不要求已有疾病文献</h2><p>导入 TCMSP、HERB 或其他获准使用的成分记录，或查询 COCONUT 天然产物。候选进入本池不需要 PMID，也不按报道数量筛除。</p><div class="research-form"><label>天然产物名称查询<input id="structureQuery" value="${esc(s.query)}" placeholder="英文成分名，例如 liquiritin"></label><button id="structureNatural" ${s.loading?'disabled':''}>查询 COCONUT 并加入候选池</button></div><div class="button-row"><label>导入成分 JSON（records 数组）<input id="structurePoolFile" type="file" accept=".json,application/json" ${s.loading?'disabled':''}></label><button id="structurePoolTemplate">下载成分格式模板</button></div>${s.pool.length?`<details><summary>成分池 ${s.pool.length} 条 · 选择一批加入计算</summary>${s.pool.map((x,i)=>`<label><input type="checkbox" data-structure-pick="${i}">${esc(x.name)} · ${esc(x.source)} ${link(x.url)}</label>`).join('')}<button id="structureUsePool" ${s.loading?'disabled':''}>将选中成分填入下方（最多 8 条）</button></details>`:''}<div class="research-form"><label>本批成分（每行一个英文名或 PubChem CID，最多 8 条）<textarea id="structureNames" rows="4" ${s.loading?'disabled':''}>${esc(s.names)}</textarea></label><label>参考分子（老师选定的已知配体）<input id="structureReference" value="${esc(s.reference)}" placeholder="英文名或 PubChem CID" ${s.loading?'disabled':''}></label><label>指定人类靶点 UniProt 编号（可选）<input id="structureAccession" value="${esc(s.accession)}" placeholder="例如 P00533；需先核对疾病关联" ${s.loading?'disabled':''}></label></div><p>计算 PubChem 二维指纹 Tanimoto 相似度；指定靶点后，另查询 ChEMBL 同一人类单蛋白靶点的结合实验记录。没有记录不等于不结合。不同实验条件不混合成亲和力评分。</p><button id="structureRun" class="primary" ${s.loading?'disabled':''}>${s.loading?'逐条查询与计算中…':'计算结构匹配并核对结合记录'}</button>${s.error?`<p role="alert" class="research-error">${esc(s.error)}</p>`:''}${results()}</section>`;}
 function poolPreview(){if(!s.pool.length)return '<div class="research-empty-state">尚未导入中药单体候选。可使用成分池模板整理获准使用的数据，不需要先有疾病论文。</div>';return `<section class="mechanism-pool-preview"><div class="section-head"><div><h3>模式二候选单体</h3><p class="mini-note">这些候选来自成分数据库或导入文件，不按疾病文献数量淘汰。</p></div><span class="pill neutral">${s.pool.length} 个候选</span></div><div class="mechanism-pool-grid">${s.pool.slice(0,50).map(x=>{const dims=[x.target||x.channel,x.affinity,x.admet,x.bbb,x.toxicity].filter(v=>v!==null&&v!==undefined&&v!=='').length;return `<article><strong>${esc(x.name)}</strong><small>${esc(x.source||'来源待核对')}${x.sourceHerb?` · ${esc(x.sourceHerb)}`:''}</small><div><span>结构 ${x.smiles||x.cid?'已有':'待补'}</span><span>机制与性质 ${dims}/5</span></div><p>${x.dimensionSource?`数据来源：${esc(x.dimensionSource)}`:'各维度来源待补充'}</p></article>`}).join('')}</div>${s.pool.length>50?`<p class="mini-note">当前预览前 50 个候选，共 ${s.pool.length} 个。</p>`:''}</section>`}
 const basePanel=panel;panel=function(){return basePanel().replace('<div class="research-form"><label>天然产物名称查询',`${poolPreview()}<div class="research-form"><label>天然产物名称查询`)};
 async function post(url,input){const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input),signal:AbortSignal.timeout(240000)});const data=await res.json();if(!res.ok)throw new Error(data.error||`查询失败（${res.status}）`);return data;}
 document.addEventListener('input',e=>{const fields={structureNames:'names',structureReference:'reference',structureAccession:'accession',structureQuery:'query'};if(fields[e.target.id]){s[fields[e.target.id]]=e.target.value;save()}});
 document.addEventListener('change',async e=>{if(e.target.id!=='structurePoolFile')return;const file=e.target.files?.[0];if(!file)return;try{if(file.size>2*1024*1024)throw new Error('成分文件不能超过 2 MB。');s.pool=parsePool(JSON.parse((await file.text()).replace(/^\uFEFF/,'')));s.error='';save();repaint()}catch(err){s.error=err.message;repaint()}});
 document.addEventListener('click',async e=>{const id=e.target.closest('button')?.id;try{
  if(id==='structurePoolTemplate')download('成分池模板.json',{provenance:{source:'填写数据库名',rawUrl:'填写来源链接',retrievedAt:''},records:[{candidateId:'C001',name:'填写英文成分名称',cid:null,smiles:'',sourceHerb:'',target:'',channel:'',affinity:'',admet:'',bbb:'',toxicity:'',dimensionSource:'每个维度的数据库、版本或链接'}]});
  if(id==='structureUsePool'){const chosen=[...document.querySelectorAll('[data-structure-pick]:checked')];if(!chosen.length||chosen.length>8)throw new Error('请选择 1–8 条成分。');s.names=chosen.map(el=>s.pool[Number(el.dataset.structurePick)]?.cid||s.pool[Number(el.dataset.structurePick)]?.name).join('\n');s.error='';save();repaint()}
  if(id==='structureRankTemplate')download('结构优先匹配待补.json',template());
  if(id==='structureExport')download('结构与结合记录.json',{inputs:{names:s.names,reference:s.reference,accession:s.accession},pool:s.pool,result:s.result,exportedAt:new Date().toISOString()});
  if(id==='structureRun'||id==='structureNatural'){
   if(s.loading)return;const names=s.names.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(id==='structureRun'&&(!names.length||names.length>8||!s.reference.trim()))throw new Error('填写 1–8 条成分和参考分子后再计算。');
   s.loading=true;s.error='';if(id==='structureRun')s.result=null;repaint();try{if(id==='structureNatural'){const d=await post('/api/natural-product',{name:s.query});const pool=parsePool({provenance:{source:'COCONUT'},records:(d.records||[]).map(r=>({...r,source:'COCONUT'}))});s.pool=pool;s.error='';}else{s.result=await post('/api/structure-screen',{names,reference:s.reference.trim(),accession:s.accession.trim()});}}finally{s.loading=false;save();repaint()}
  }
 }catch(err){s.loading=false;s.error=err.message;save();repaint()}});
 window.StructureUI={panel,parsePool,template};
})();
