'use strict';
const test = require('node:test'); const assert = require('node:assert/strict'); const { createResearchService, ResearchError } = require('./research.cjs');
function mockFetch(routes, calls = []) { return async (url) => { calls.push(String(url)); const route = routes.find(x => (x[0]==='esearch' ? String(url).includes('/esearch.fcgi') : String(url).includes(x[0]))); if (!route) return { ok: false, status: 500, json: async () => ({}) }; const value = route[1]; return { ok: true, status: 200, json: async () => typeof value === 'function' ? value(url) : value, text: async () => typeof value === 'function' ? value(url) : value }; }; }
test('aliases are translated and records retain provenance', async () => { const calls=[]; const fetchImpl=mockFetch([['esearch', {esearchresult:{count:'1',idlist:['7']}}], ['esummary',{result:{'7':{title:'Study',source:'J',pubdate:'2020',articleids:[{idtype:'doi',value:'10.x'}]}}}], ['efetch','<PubmedArticle><MedlineCitation><PMID>7</PMID></MedlineCitation><Article><Abstract><AbstractText>Plants &amp; health</AbstractText></Abstract></Article></PubmedArticle>'], ['pubtator', {documents:[]}]],calls); const r=await createResearchService({fetchImpl,minIntervalMs:0}).search({disease:'三叉神经痛'}); assert.equal(r.disease.term,'trigeminal neuralgia'); assert.equal(r.records[0].abstract,'Plants & health'); assert.match(r.records[0].url,/pubmed.ncbi.nlm.nih.gov/); assert.equal(calls.length,4); });
test('PubTator array and object forms produce bounded chemical candidates', async () => { const bio=[{id:'7',passages:[{text:'Aspirin study',annotations:[{text:'Aspirin',infons:{type:'Chemical',identifier:'CID:2244'}}]}]}]; const f=mockFetch([['esearch',{esearchresult:{count:'1',idlist:['7']}}],['esummary',{result:{'7':{title:'T',source:'J'}}}],['efetch','<x/>'],['pubtator',{PubTator3:bio}]]); const r=await createResearchService({fetchImpl:f,minIntervalMs:0}).search({disease:'inflammation'}); assert.equal(r.candidates[0].identifier,'CID:2244'); assert.equal(r.candidates[0].status,'机器识别·待核验'); });
test('zero hits differ from upstream failure', async () => { const zero=await createResearchService({fetchImpl:mockFetch([['esearch',{esearchresult:{count:'0',idlist:[]}}]]),minIntervalMs:0}).search({disease:'lung cancer'}); assert.equal(zero.total,0); assert.deepEqual(zero.records,[]); const fail=async()=>({ok:false,status:503,json:async()=>({})}); await assert.rejects(()=>createResearchService({fetchImpl:fail,minIntervalMs:0}).search({disease:'lung cancer'}), e=>e.status===502); });
test('blocked or malformed PubMed falls back to Europe PMC and indexes chemicals', async () => { const calls=[]; const f=async url => { calls.push(String(url)); if (String(url).includes('/esearch.fcgi')) return {ok:true,status:200,json:async()=>{throw new Error('HTML block page')}}; return {ok:true,status:200,json:async()=>({hitCount:1,resultList:{result:[{id:'41880679',pmid:'41880679',source:'MED',title:'Study',journalInfo:{journal:{title:'Journal'}},firstPublicationDate:'2024-01-01',doi:'10.x',abstractText:'<p>Abstract</p>',chemicalList:{chemical:[{name:'liquiritin',registryNumber:'T0O79T74CD'},{name:'generic protein',registryNumber:'0'}]}}]}})}; }; const r=await createResearchService({fetchImpl:f,minIntervalMs:0}).search({disease:'inflammation'}); assert.equal(r.source,'Europe PMC（PubMed记录）'); assert.equal(r.provider,'Europe PMC'); assert.match(r.query,/SRC:MED/); assert.match(r.query,/sort_date:y/); assert.equal(r.records[0].pmid,'41880679'); assert.equal(r.records[0].abstract,'Abstract'); assert.equal(r.candidates[0].identifier,'T0O79T74CD'); assert.equal(r.candidates[0].source,'Europe PMC化学索引'); assert.match(r.warnings[0],/PubMed 不可用/); assert.ok(calls.some(x=>x.includes('europepmc'))); });
test('malformed Europe PMC result is an error, not zero hits', async () => { const f=async url => String(url).includes('/esearch.fcgi') ? {ok:true,status:200,json:async()=>({error:'blocked'})} : {ok:true,status:200,json:async()=>({hitCount:0,resultList:{}})}; await assert.rejects(()=>createResearchService({fetchImpl:f,minIntervalMs:0}).search({disease:'inflammation'}), e=>e.status===502 && /Europe PMC/.test(e.message)); });
test('PubChem preserves CID and reports 404', async () => { const r=await createResearchService({fetchImpl:mockFetch([['pubchem',{PropertyTable:{Properties:[{CID:2244,MolecularFormula:'C9H8O4',MolecularWeight:180.16,InChIKey:'X',IUPACName:'acid'}]}}]]),minIntervalMs:0}).compound('aspirin'); assert.equal(r.cid,2244); assert.equal(r.identityStatus,'needs_review'); const missing=async()=>({ok:false,status:404,json:async()=>({})}); await assert.rejects(()=>createResearchService({fetchImpl:missing,minIntervalMs:0}).compound('x'), e=>e.status===404); });
test('cache and inflight coalesce', async () => { let n=0; const f=async url=>{n++; return mockFetch([['esearch',{esearchresult:{count:'0',idlist:[]}}]])(url); }; const s=createResearchService({fetchImpl:f,minIntervalMs:0}); const [a,b]=await Promise.all([s.search({disease:'inflammation'}),s.search({disease:'inflammation'})]); assert.equal(n,1); assert.equal((await s.search({disease:'inflammation'})).cached,true); assert.equal(a.total,b.total); });
test('hostile and unknown input rejected', async () => { const s=createResearchService({fetchImpl:mockFetch([]),minIntervalMs:0}); await assert.rejects(()=>s.search({disease:'未知病种'}), e=>e.status===400); await assert.rejects(()=>s.search({disease:'lung cancer',target:'x'.repeat(101)}), e=>e.status===400); await assert.rejects(()=>s.compound(''), e=>e.status===400); });
