'use strict';
const UNIPROT='https://rest.uniprot.org/uniprotkb/search';
const CHEMBL='https://www.ebi.ac.uk/chembl/api/data';
const EPMC='https://www.ebi.ac.uk/europepmc/webservices/rest/search';
class SourceError extends Error { constructor(message,status=502){super(message);this.name='SourceError';this.status=this.statusCode=status;} }
function clean(v,n,max=80){if(typeof v!=='string')throw new SourceError(`${n} must be text`,400);const s=v.trim();if(!s||s.length>max||/[\u0000-\u001f\u007f<>`"'\\]|(?:https?:)?\/\//i.test(s))throw new SourceError(`${n} is invalid`,400);return s;}
function envelope(source,records,total,warnings=[],extra={}){return {source,retrievedAt:new Date().toISOString(),records,total,warnings,...extra};}
function createSourceService(options={}){
 const fetchImpl=options.fetchImpl||global.fetch;if(typeof fetchImpl!=='function')throw new TypeError('fetchImpl is required');
 const timeoutMs=Math.max(250,Math.min(30000,Number(options.timeoutMs)||20000)),ttl=Math.max(0,Math.min(3600000,Number(options.cacheTtlMs)||300000));const cache=new Map(),inflight=new Map();
 async function request(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeoutMs);let r;try{r=await fetchImpl(url,{signal:c.signal,headers:{accept:'application/json'}});if(!r?.ok)throw new SourceError(r?.status===404?'Official source record not found':'Official source request failed',r?.status===404?404:502);const data=await r.json();return {data,totalHeader:Number(r.headers?.get?.('x-total-results')||NaN)};}catch(e){if(e instanceof SourceError)throw e;if(e?.name==='AbortError')throw new SourceError('Upstream request timed out',504);throw new SourceError('Unable to reach official source',502);}finally{clearTimeout(t);}}
 async function cached(key,work){const h=cache.get(key);if(h&&h.expires>Date.now())return {...h.value,cached:true};if(inflight.has(key))return inflight.get(key);const p=(async()=>{const v=await work();cache.set(key,{value:v,expires:Date.now()+ttl});while(cache.size>100)cache.delete(cache.keys().next().value);return v;})();inflight.set(key,p);try{return await p;}finally{inflight.delete(key);}}
 async function target(query){const q=clean(query,'query',30);if(!/^[A-Za-z0-9_-]+$/.test(q))throw new SourceError('请输入一个基因符号，例如 EGFR 或 SCN9A',400);const dsl=`gene_exact:${q} AND organism_id:9606 AND reviewed:true`;if(dsl.length>80)throw new SourceError('query is too long',400);return cached(`target:${dsl}`,async()=>{const r=await request(`${UNIPROT}?query=${encodeURIComponent(dsl)}&format=json&size=20&fields=accession,id,gene_names,protein_name,organism_name,cc_function`),d=r.data;if(!d||!Array.isArray(d.results))throw new SourceError('UniProt returned invalid JSON',502);const records=d.results.slice(0,20).map(x=>({accession:String(x.primaryAccession||''),id:String(x.uniProtkbId||''),url:x.primaryAccession?`https://www.uniprot.org/uniprotkb/${encodeURIComponent(x.primaryAccession)}/entry`:'',gene:String(x.genes?.[0]?.geneName?.value||''),protein:String(x.proteinDescription?.recommendedName?.fullName?.value||''),organism:String(x.organism?.scientificName||''),reviewed:x.entryType==='UniProtKB reviewed (Swiss-Prot)'||x.entryType==='UniProtKB reviewed',function:String(x.comments?.find?.(z=>z.commentType==='FUNCTION')?.texts?.[0]?.value||'')})).filter(x=>x.accession);const total=Number.isFinite(r.totalHeader)?r.totalHeader:Number(d.totalResults??records.length);return envelope('UniProt',records,total,[],{query:q,cached:false});});}
 async function molecule(name){const q=clean(name,'name',100);return cached(`molecule:${q}`,async()=>{const d=(await request(`${CHEMBL}/molecule/search.json?q=${encodeURIComponent(q)}&limit=5`)).data;if(!d||!Array.isArray(d.molecules))throw new SourceError('ChEMBL returned invalid JSON',502);const records=d.molecules.slice(0,5).map(x=>({moleculeId:String(x.molecule_chembl_id||''),name:String(x.pref_name||''),maxPhase:x.max_phase??null,smiles:String(x.molecule_structures?.canonical_smiles||''),inchiKey:String(x.molecule_structures?.standard_inchi_key||''),url:x.molecule_chembl_id?`https://www.ebi.ac.uk/chembl/explore/compound/${encodeURIComponent(x.molecule_chembl_id)}`:''})).filter(x=>x.moleculeId);return envelope('ChEMBL',records,Number(d.page_meta?.total_count??records.length),[],{query:q,cached:false});});}
 async function bioactivity(moleculeId){const id=clean(moleculeId,'moleculeId',32).toUpperCase();if(!/^CHEMBL\d+$/.test(id))throw new SourceError('moleculeId must be a ChEMBL ID',400);return cached(`activity:${id}`,async()=>{const d=(await request(`${CHEMBL}/activity.json?molecule_chembl_id=${encodeURIComponent(id)}&limit=20&offset=0`)).data;if(!d||!Array.isArray(d.activities))throw new SourceError('ChEMBL returned invalid JSON',502);const records=d.activities.slice(0,20).map(a=>({activityId:a.activity_id??null,assay:{id:a.assay_chembl_id||null,description:a.assay_description||'',type:a.assay_type||null},target:{id:a.target_chembl_id||null,type:a.target_type||null,organism:a.target_organism||null,name:a.target_pref_name||a.target_name||null},relation:a.standard_relation||a.relation||null,type:a.standard_type||a.type||null,value:a.standard_value??a.value??null,units:a.standard_units||a.units||null,validity:a.activity_comment||a.data_validity_comment||null,flags:{potentialDuplicate:Boolean(a.potential_duplicate),uncertain:Boolean(a.data_validity_comment)},document:{id:a.document_chembl_id||null,doi:a.document_doi||null,pmid:a.document_pmid||null,citation:a.document_journal||a.document_year||null,url:a.document_chembl_id?`https://www.ebi.ac.uk/chembl/explore/document/${encodeURIComponent(a.document_chembl_id)}`:''}}));return envelope('ChEMBL',records,Number(d.page_meta?.total_count??records.length),[],{moleculeId:id,cached:false});});}
 async function article(pmid){const id=clean(pmid,'pmid',20);if(!/^\d{1,12}$/.test(id))throw new SourceError('pmid must be numeric',400);return cached(`article:${id}`,async()=>{const query=`EXT_ID:${id} AND SRC:MED`,d=(await request(`${EPMC}?query=${encodeURIComponent(query)}&resultType=core&format=json&pageSize=1`)).data;if(!d?.resultList||!Array.isArray(d.resultList.result)||!Number.isFinite(Number(d.hitCount)))throw new SourceError('Europe PMC returned invalid JSON',502);const x=d.resultList.result[0];if(!x||String(x.pmid||x.id||'')!==id)throw new SourceError('Article not found',404);const pmcid=String(x.pmcid||'');const urls=Array.isArray(x.fullTextUrlList?.fullTextUrl)?x.fullTextUrlList.fullTextUrl.map(z=>({url:String(z.url||''),availability:z.availability||null})).filter(z=>/^https:\/\//.test(z.url)):[];const record={pmid:id,title:String(x.title||''),journal:String(x.journalInfo?.journal?.title||x.journalTitle||''),date:String(x.firstPublicationDate||''),doi:String(x.doi||''),abstract:String(x.abstractText||'').replace(/<[^>]+>/g,'').trim(),pmcid:pmcid||null,openAccess:x.isOpenAccess===true||x.isOpenAccess==='Y',links:{pubmed:`https://pubmed.ncbi.nlm.nih.gov/${id}/`,europePmc:`https://europepmc.org/article/MED/${id}`,pmc:pmcid?`https://europepmc.org/articles/${encodeURIComponent(pmcid)}/`:null,fullText:urls}};return envelope('Europe PMC',[record],1,[],{query,cached:false});});}
 return {target,molecule,bioactivity,article,SourceError};
}
module.exports={createSourceService,SourceError};
